# Quadratic Score

Quadratic Discriminant Score and Cluster Quality Criteria
(Coraggio & Coretto, 2023)


"""
Coraggio & Coretto (2023) introduced two cluster-quality criteria derived 
from the quadratic discriminant score:

- Hard Score (Hₙ): assigns each point to the cluster whose quadratic score 
  is the highest (crisp assignment).
- Smooth Score (Tₙ): uses a soft weighting via a softmax transformation 
  of those scores, leading to smoother membership assignments.
"""

Quadratic Score
For a point xᵢ and clusters defined by parameters θₖ = (πₖ, μₖ, Σₖ):

$qs(xᵢ, θₖ) = log(πₖ) - 1/2 * log det(Σₖ) - 1/2 * (xᵢ - μₖ)ᵀ Σₖ⁻¹ (xᵢ - μₖ)$

Soft Membership (Weights)
The soft membership weight of point xᵢ in cluster k is:

$τₖ(xᵢ; θ) = exp(qs(xᵢ, θₖ)) / ∑ⱼ exp(qs(xᵢ, θⱼ))$ (i.e., a softmax transformation of the scores)

Smooth Score
The smooth score is defined as:

$Tₙ(θ) = (1/n) ∑ᵢ ∑ₖ τₖ(xᵢ; θ) · qs(xᵢ, θₖ)$

# Initialisation

In [25]:
## Set up
## Import Packages
import warnings
import os
import sys

import pandas as pd
import numpy as np
import re # Regular Expressions

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.patches as patches

# import seaborn as sns
# import plotly.express as px

import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, SpectralClustering
from sklearn.metrics import silhouette_score, silhouette_samples, adjusted_rand_score, fowlkes_mallows_score, davies_bouldin_score, calinski_harabasz_score
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.model_selection import train_test_split
from sklearn.manifold import TSNE

import scipy
from scipy.spatial.distance import cdist
from scipy.stats import norm, skew, kurtosis, spearmanr
from scipy.optimize import linear_sum_assignment
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

from joblib import Parallel, delayed

# Time functions
import time
 
# Suppress Future Warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Suppress print() in functions
# import contextlib
import io

# Suppress prints
from contextlib import redirect_stdout

def suppress_print(func, *args, **kwargs):
    with open(os.devnull, "w") as fnull, redirect_stdout(fnull):
        return func(*args, **kwargs)

#Create Logs
import logging
logging.basicConfig(
    filename='debug_BQS.log',
    filemode='w',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    force=True
)

# Data Storage Location:
data_storage = "/Users/pattydegroot/Documents/Python/PsAID-Cluster-Analysis/Quadratic Scores"

# Select Random Seed
RandomSeed = 42
print(f'Random seed is set to {RandomSeed}. Cluster algorithms and Neural Networks are optimization algorithms. Therefore the seed affects the initialization and so the model performance.')

Random seed is set to 42. Cluster algorithms and Neural Networks are optimization algorithms. Therefore the seed affects the initialization and so the model performance.

### Choose Settings

In [26]:
compute = True
save_results = False

if compute == True:
    test = False
    storage_location= '/Users/pattydegroot/Documents/Python/PsAID-Cluster-Analysis/PsAID_Pre-Processing & Inspection'
    algorithms = ['HAC_ward'] #['HAC_ward'] #['kmeans', 'HAC_ward', 'Spectral_Density']
    "n_bootstrap staat voor nu op b=100 omdat het computeren van de HAC wat meer tijd kost. Zou eigenlijk 1000 moeten zijn"

if not compute:
    test = True  # Uses iris dataset + kmeans
    algorithms = ['kmeans']
    "The example with kmeans implements the 'Hartigan & Wong kmeans algorithm, whilst the sklean kmeans applies Lloyd’s algorithm or Elkan if specifically defined"

## Import Dataset

In [27]:
if test:
    print('dataset = iris')
    dataset = sns.load_dataset("iris")
    columns_gp = ['sepal_length', 'sepal_width',  'petal_length',  'petal_width']
    print(dataset.head())
    dataset.info()

if compute:
    print('dataset = PsAID')
    ## Import Dataset
    dataset = pd.read_csv(f'{storage_location}/PsAID_Preprocessed.csv') # Import dataset
    dataset.head() # Check data
    
    ## Define Varlists
    columns_gp = [i for i in dataset.columns if re.match(r'^gp\d{2}$',i)]
    dataset = dataset[['respondentid', 'mm']+columns_gp]
    
    ## Dictionary
    domains_dict = {
        'gp01': 'Pain',
        'gp02': 'Fatigue',
        'gp03': 'Skin',
        'gp04': 'Work-recreational activities',
        'gp05': 'Bodily functioning',
        'gp06': 'Discomfort',
        'gp07': 'Sleep',
        'gp08': 'Coping',
        'gp09': 'Anxiety',
        'gp10': 'Shame',
        'gp11': 'Social activities',
        'gp12': 'Depression'
    }
    dataset.info()

dataset = PsAID
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   respondentid  5099 non-null   int64
 1   mm            5099 non-null   int64
 2   gp01          5099 non-null   int64
 3   gp02          5099 non-null   int64
 4   gp03          5099 non-null   int64
 5   gp04          5099 non-null   int64
 6   gp05          5099 non-null   int64
 7   gp06          5099 non-null   int64
 8   gp07          5099 non-null   int64
 9   gp08          5099 non-null   int64
 10  gp09          5099 non-null   int64
 11  gp10          5099 non-null   int64
 12  gp11          5099 non-null   int64
 13  gp12          5099 non-null   int64
dtypes: int64(14)
memory usage: 557.8 KB

# Bootstrap

## Cluster

### Kmeans

In [28]:
def kmeans_clustering(data, n_clusters, RandomSeed, byvar):   

    # Initialize and fit the KMeans model
    kmeans = KMeans(
        n_clusters=n_clusters,
        init='k-means++',
        n_init='auto',
        random_state= RandomSeed
    )
    clusterID = f'clusterID_KM_k{n_clusters}'
    data[clusterID] = kmeans.fit_predict(data[byvar]) #Assign cluster to each datapoint and store in the dataset dataframe

    del kmeans #Ensure the model is forgotten after each iteration
    return data, clusterID

### Hierarchical

In [29]:
def HAC_ward_clustering(data, k):
    """
    Because our dataset is based on whole numbers [0-10], the HAC ward clustering is sensitive to the scale of the data. 
    There is higher similarity because of the lack of variance. Meaning that when scaled ties are assigned differently.
    """
    #link = 'ward'
    link = 'complete'
    #link = 'average'
    distance_metric = 'euclidean' # Ward can only be performed with euclidean distance
    #distance_metric = 'manhattan'
    # thresholds = {2:400, 3:230, 5:130, 7:100} # Ward
    # thresholds = {2:33, 3:26, 4:23}   # Complete

    if distance_metric == 'manhattan':
        linkage_matrix_distance = 'cityblock'
        distance_suffix = 'L1'
    else:
        linkage_matrix_distance = distance_metric
        distance_suffix = ''
    
    # Run agglomeration algorithm
    HAC_Ward = AgglomerativeClustering(n_clusters=10, linkage = link, metric = distance_metric).fit(data[columns_gp])
    
    # Create linkage matrix
    linkage_matrix = linkage(data[columns_gp], method=link, metric = linkage_matrix_distance)
    
    # Assign Clusters
    cluster_assignment = fcluster(linkage_matrix, k, criterion = 'maxclust')-1 #flcuster outputs clusters as 1-K, but we need 0-K for consistency across techniques
    #cluster_assignment = fcluster(linkage_matrix, t=thresholds[k], criterion = 'distance')-1 #flcuster outputs clusters as 1-K, but we need 0-K for consistency across techniques
    n_clusters = len(np.unique(cluster_assignment))

    """ Cuts can produce different n_clusters, therefor use K. Kan be that K=3 has 4 clusters """
    clusterID = f'clusterID_HAC{link}_k{k}' #
    
    data[clusterID] = cluster_assignment
    # print(data.head())

    # PRINTS FOR DEBUGGING
    print(f'k:{n_clusters}')
    print(f'sizes: {data[clusterID].value_counts().sort_index().values}')
    print(clusterID)
    
    # # Plot Dendrogram
    # plt.figure(figsize=(10,7))
    # dendrogram(linkage_matrix, labels=data[columns_gp].index, leaf_rotation=90, leaf_font_size=8)
    # plt.title(f'Hierarchical Clustering Dendrogram, link {link}')
    # plt.xlabel("Sample Index")
    # plt.ylabel(f'Distance {distance_metric}')
    # for t in [2, 3, 5, 7]:
    #     plt.axhline(y=thresholds[t])
    # plt.show()

    del HAC_Ward
    return data, clusterID

### Spectral

In [30]:
def scale_data(data, scaling):
    """ ATTENTION: THE SCALE OF THE DATA AFFECTS THE QS SCORE THROUGH THE LOGDET(), This is solved when computing the BQS by only returning the cluster assignments and merge it with the original data"""
    if scaling == 'div10':
         data_scaled = data/10
    elif scaling == 'StandardScaled':
         scaler = StandardScaler()
         data_scaled = pd.DataFrame(
            scaler.fit_transform(data[columns_gp]),      # Only values are transformed
            columns=columns_gp,            # Keep original column names
            index=data[columns_gp].index                 # Optional: keep original index
         )

    return data_scaled

def spectral_clustering(data_scaled, settings, RandomSeed):
    settings = settings.copy()
    scaling = settings.pop('scaling') # Remove item from dict and return value

    # Initialize and fit the KMeans model
    spec_clust = SpectralClustering(**settings,
                    # n_clusters=k, 
                    # affinity = aff,
                    # gamma = gamma,
                    # assign_labels=ass,
                    random_state=RandomSeed
    )

    # Fit the model and get the predicted labels
    clusterID = f'clusterID_{scaling}_{settings['affinity']}{settings['gamma']}_{settings['assign_labels']}_k{settings['n_clusters']}'
    cluster_assignment = spec_clust.fit_predict(data_scaled)

    # # Save the embedding layer
    # # Extract the spectral embedding used by SpectralClustering()
    # embedding = spectral_embedding(
    #     adjacency=spec_clust.affinity_matrix_,
    #     n_components=cluster,
    #     random_state=RandomSeed
    # )

    del spec_clust
    return clusterID, cluster_assignment

def run_spectral_clustering(data, settings, byvar, RandomSeed):

    # Scale data for easy computation
    data_scaled = scale_data(data[byvar], settings['scaling'])

    # Spectral Projection + Clustering
    clusterID, cluster_assignment = spectral_clustering(data_scaled, settings, RandomSeed)

    # Add clusters to dataset
    data = data.copy()
    data[clusterID] = cluster_assignment

    return data, clusterID

In [31]:
for algorithm in algorithms:
    print(algorithm)
    if algorithm == 'kmeans':
        for k in range(2,11): 
            dataset, clusterID = kmeans_clustering(dataset, k, RandomSeed, columns_gp)
            #clusterID
    if algorithm == 'HAC_ward':
        for k in [2,3,4, 5,7]:
            dataset, clusterID = HAC_ward_clustering(dataset, k)
    if algorithm == 'Spectral_Density': 
        spectral_settings = { # K3 DIV 10
                              "run_K3A":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 3.9 , "assign_labels": 'cluster_qr'},
                              "run_K3B":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 3.9, "assign_labels": 'cluster_qr'},
                              "run_K3C":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 3.9, "assign_labels": 'cluster_qr'},
                              "run_K3D":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'cluster_qr'},
                              "run_K3E":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'cluster_qr'},
                              }
                             
        for sett in spectral_settings:
             dataset, clusterID = run_spectral_clustering(dataset, spectral_settings[sett], columns_gp, RandomSeed)

dataset

HAC_ward
k:2
sizes: [ 383 4716]
clusterID_HACcomplete_k2
k:3
sizes: [ 383 3697 1019]
clusterID_HACcomplete_k3
k:4
sizes: [ 383 3697  179  840]
clusterID_HACcomplete_k4
k:5
sizes: [ 383 3697  179   87  753]
clusterID_HACcomplete_k5
k:7
sizes: [ 383  673 2420  604  179   87  753]
clusterID_HACcomplete_k7

,respondentid,mm,gp01,gp02,gp03,gp04,gp05,gp06,gp07,gp08,gp09,gp10,gp11,gp12,clusterID_HACcomplete_k2,clusterID_HACcomplete_k3,clusterID_HACcomplete_k4,clusterID_HACcomplete_k5,clusterID_HACcomplete_k7
0,78195329,36,2,2,2,2,2,0,1,0,0,0,0,0,1,1,1,1,2
1,10862915,6,1,6,2,1,1,1,1,1,1,0,0,2,1,1,1,1,1
2,29370588,18,6,7,5,6,4,6,7,5,6,2,8,5,1,2,2,2,4
3,87648336,18,0,4,5,0,0,0,0,0,0,1,0,0,1,1,1,1,3
4,42677901,84,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5094,48031533,0,3,4,1,2,2,3,2,2,1,0,2,1,1,1,1,1,2
5095,71662504,9,3,3,0,6,6,3,0,6,6,0,1,1,1,1,1,1,3
5096,63159202,18,7,8,10,8,8,10,10,10,10,10,9,10,0,0,0,0,0
5097,36477829,36,7,6,0,6,6,6,6,6,6,4,6,4,1,2,3,4,6
5098,30552881,24,0,6,0,3,4,0,0,0,0,0,0,0,1,1,1,1,2

# All Spectral Density Settings tried
# spectral_settings = { # K3 DIV 10
                              #"run_K3A":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 3.9 , "assign_labels": 'cluster_qr'},
                              # "run_K3B":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 3.9, "assign_labels": 'kmeans' },
                              # "run_K3C":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'cluster_qr'},
                              # "run_K3D":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'kmeans' },
                              # "run_K3E":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'cluster_qr'},
                              # "run_K3F":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'kmeans' },
                              # "run_K3G":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'cluster_qr'},
                              # "run_K3H":{"scaling": 'div10', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'kmeans' },
                            # K3 STANDARD SCALED  
                               # "run_K3A":{"scaling": 'StandardScaled', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 0.22 , "assign_labels": 'cluster_qr'},
                               # "run_K3B":{"scaling": 'StandardScaled', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 0.22, "assign_labels": 'kmeans' },
                               # "run_K3C":{"scaling": 'StandardScaled', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'cluster_qr'},
                               # "run_K3D":{"scaling": 'StandardScaled', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'kmeans' },
                               # "run_K3E":{"scaling": 'StandardScaled', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'cluster_qr'},
                               # "run_K3F":{"scaling": 'StandardScaled', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'kmeans' },
                               # "run_K3G":{"scaling": 'StandardScaled', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'cluster_qr'},
                               # "run_K3H":{"scaling": 'StandardScaled', "n_clusters": 3 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'kmeans' }
                            # K4 DIV 10
                             # "run_K4A":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 3.9 , "assign_labels": 'cluster_qr'},
                             # "run_K4B":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 3.9, "assign_labels": 'kmeans' },
                             # "run_K4C":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'cluster_qr'},
                             # "run_K4D":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'kmeans' },
                             # "run_K4E":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'cluster_qr'},
                             # "run_K4F":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'kmeans' },
                             # "run_K4G":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'cluster_qr'},
                             # "run_K4H":{"scaling": 'div10', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'kmeans' },
                            # K4 DIV 10
                             # "run_K4A":{"scaling": 'StandardScaled', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 0.22 , "assign_labels": 'cluster_qr'},
                             # "run_K4B":{"scaling": 'StandardScaled', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 0.22, "assign_labels": 'kmeans' },
                             # "run_K4C":{"scaling": 'StandardScaled', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'cluster_qr'},
                             # "run_K4D":{"scaling": 'StandardScaled', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'kmeans' },
                             # "run_K4E":{"scaling": 'StandardScaled', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'cluster_qr'},
                             # "run_K4F":{"scaling": 'StandardScaled', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'kmeans' },
                             # "run_K4G":{"scaling": 'StandardScaled', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'cluster_qr'},
                             # "run_K4H":{"scaling": 'StandardScaled', "n_clusters": 4 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'kmeans' },
                            #K5 DIV 10
                             # "run_K5A":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 3.9 , "assign_labels": 'cluster_qr'},
                             # "run_K5B":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 3.9, "assign_labels": 'kmeans' },
                             # "run_K5C":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'cluster_qr'},
                             # "run_K5D":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'kmeans' },
                             # "run_K5E":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'cluster_qr'},
                             # "run_K5F":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'kmeans' },
                             # "run_K5G":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'cluster_qr'},
                             # "run_K5H":{"scaling": 'div10', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'kmeans' },
                            # K5 Standard Scaled
                             # "run_K5A":{"scaling": 'StandardScaled', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 0.22 , "assign_labels": 'cluster_qr'},
                             # "run_K5B":{"scaling": 'StandardScaled', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 0.22, "assign_labels": 'kmeans' },
                             # "run_K5C":{"scaling": 'StandardScaled', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'cluster_qr'},
                             # "run_K5D":{"scaling": 'StandardScaled', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'kmeans' },
                             # "run_K5E":{"scaling": 'StandardScaled', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'cluster_qr'},
                             # "run_K5F":{"scaling": 'StandardScaled', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'kmeans' },
                             # "run_K5G":{"scaling": 'StandardScaled', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'cluster_qr'},
                             # "run_K5H":{"scaling": 'StandardScaled', "n_clusters": 5 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'kmeans' },
                            # K6 Div 10
                             # "run_K6A":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 3.9 , "assign_labels": 'cluster_qr'},
                             # "run_K6B":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 3.9, "assign_labels": 'kmeans' },
                             # "run_K6C":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'cluster_qr'},
                             # "run_K6D":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'kmeans' },
                             # "run_K6E":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'cluster_qr'},
                             # "run_K6F":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'kmeans' },
                             # "run_K6G":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'cluster_qr'},
                             # "run_K6H":{"scaling": 'div10', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'kmeans' },
                            # K6 Standard Scaled
                             # "run_K6A":{"scaling": 'StandardScaled', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 0.22 , "assign_labels": 'cluster_qr'},
                             # "run_K6B":{"scaling": 'StandardScaled', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 0.22, "assign_labels": 'kmeans' },
                             # "run_K6C":{"scaling": 'StandardScaled', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'cluster_qr'},
                             # "run_K6D":{"scaling": 'StandardScaled', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'kmeans' },
                             # "run_K6E":{"scaling": 'StandardScaled', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'cluster_qr'},
                             # "run_K6F":{"scaling": 'StandardScaled', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'kmeans' },
                             # "run_K6G":{"scaling": 'StandardScaled', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'cluster_qr'},
                             # "run_K6H":{"scaling": 'StandardScaled', "n_clusters": 6 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'kmeans' },
                            # K7 Div 10
                             # "run_K7A":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 3.9 , "assign_labels": 'cluster_qr'},
                             # "run_K7B":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 3.9, "assign_labels": 'kmeans' },
                             # "run_K7C":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'cluster_qr'},
                             # "run_K7D":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 4.5, "assign_labels": 'kmeans' },
                             # "run_K7E":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'cluster_qr'},
                             # "run_K7F":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 5.1, "assign_labels": 'kmeans' },
                             # "run_K7G":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'cluster_qr'},
                             # "run_K7H":{"scaling": 'div10', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 5.7, "assign_labels": 'kmeans' }
                            # K7 Standard Scaled
                             # "run_K7A":{"scaling": 'StandardScaled', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 0.22 , "assign_labels": 'cluster_qr'},
                             # "run_K7B":{"scaling": 'StandardScaled', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 0.22, "assign_labels": 'kmeans' },
                             # "run_K7C":{"scaling": 'StandardScaled', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'cluster_qr'},
                             # "run_K7D":{"scaling": 'StandardScaled', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 0.33, "assign_labels": 'kmeans' },
                             # "run_K7E":{"scaling": 'StandardScaled', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'cluster_qr'},
                             # "run_K7F":{"scaling": 'StandardScaled', "n_clusters": 7,"affinity": 'rbf', "gamma": 0.55, "assign_labels": 'kmeans' },
                             # "run_K7G":{"scaling": 'StandardScaled', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'cluster_qr'},
                             # "run_K7H":{"scaling": 'StandardScaled', "n_clusters": 7 ,"affinity": 'rbf', "gamma": 0.73, "assign_labels": 'kmeans' },
#                             }

# Compute QS

The quadratic smooth criterion looks for a compromise between the best approximation of the finite mixture density ($\psi$)

1. Compute cluster representations ($\theta_{k}$)
   - $\pi_{k}$ = size --> fraction of points belonging to cluster k
   - $\mu_{k}$ = location --> cluster centers
   - $\Sigma_{k}$ = scatter --> pos.def scatter matrix, which coincides / is proportional to cov. matrix <br>
       If the cluster has very few points OR some features are linearly dependent the matrix can be singular and thus not invertible.

2. Compute the quadratic score ($qs$) for each point in each cluster. <br>
    The quadratic score is a measure of fit of $X$ into the $k^{th}$ cluster according to $\theta_{k}$

4. Compute the Quadratic Smooth Score ($T_{n}(\theta)$) <br>
    Smooth weighting ($\tau$) is obtained by normalizing the quadratic scores with softmax transformation. Other weighting schemes are possible, but softmax guarantees some form of optimality for Gaussian clusters. 
    - $T_n(\theta) = \frac{1}{n} \sum_{i=1}^{n} \sum_{k=1}^{K} \tau_k(x_i; \theta) \, qs(x_i; \theta_k)$ ^ $\tau_k(x_i; \theta) = \frac{\exp(qs(x_i; \theta_k))}{\sum_{j=1}^{K} \exp(qs(x_i; \theta_j))}$ <br>

In [32]:
def compute_QS(data, byvar, cluster_col):
   
    n,p = data.shape  # Num_rows, Num_columns
    labels = data[cluster_col] # Cluster assignments
    k = len(labels.unique()) # Number of clusters
    print(f'K:{k}')

    print(f'\n Computing QS for {cluster_col}')

    # Extract parameters
    cluster_size = labels.value_counts().sort_index().values # Array of cluster sizes
    cluster_sizefraction = labels.value_counts().sort_index().values/n # Fraction of the sample belonging to each cluster
    cluster_centers = data[byvar + [cluster_col]].groupby(cluster_col).mean()  # Centroid vector
    print('cluster_size:', cluster_size)

    # ---- validity check ----
    # Check for singular mixture components. If <2 the cov matrix is undefined/dof<=0 -->  If singular the $inv(Sigma_k)$ can not be computed because det(Sigma_k) = 0.
    # Thus can't calculate Tn
    if np.any(cluster_size <2):
        Tn = np.nan
        tau = np.nan
        if len(labels.unique()) != int(re.search(r'k(\d+)', cluster_col).group(1)): 
            comments = f'k ≠ label & cluster {np.where(cluster_size < 2)[0].tolist()} invalid'
        else:    
            comments = f'cluster {np.where(cluster_size < 2)[0].tolist()} invalid'
        return Tn, tau, comments, cluster_size
 
    # Compute Quadratic Score qs
    X = data[byvar].to_numpy() #Convert psaid data to numpy array
    qs_matrix = np.full((n, k), np.nan)  # Reserve space for qs_matrix
    
    for k in sorted(labels.unique()):

        pi_k = cluster_sizefraction[k] # Fraction of cluster k
        mu_k = cluster_centers.loc[k].to_numpy() # Centers of cluster k

        # Compute scatter/covariance
        cluster_data = data.loc[labels == k, byvar]
        Sig_k = np.cov(cluster_data, rowvar=False, ddof=1) # Compute sample scatter = covariance matrix of cluster k

        # Check for linear dependencies --> Compute Rank of sample 
        # If the cov matrix is singular --> Ridge regularization to make invertible
        if np.linalg.matrix_rank(Sig_k) < len(byvar): 
            Sig_k += 1e-6 * np.eye(len(byvar))

        # Compute the quadratic term = 1/2 * (xᵢ - μₖ)ᵀ Σₖ⁻¹ (xᵢ - μₖ)
        diff = X - mu_k # Difference Vectors
        inv_Sig = np.linalg.inv(Sig_k) #Log DEeterminant
        quad = np.einsum('ij,jk,ik->i', diff, inv_Sig, diff) # Quadratic term = Mahalanobis distance squared # Einsum lets you define custom summation patterns

        # Compute Log Determinant of Sig_k
        # By using slogdet and ignoring sign, Sig_k is assumed positive-definite, which is usually fine if you regularize
        sign, logdet = np.linalg.slogdet(Sig_k)
 
        # Compute the Quadratice Scores for all observations in cluster k
        qs = np.log(pi_k)-0.5*logdet-0.5*quad
        qs_matrix[:,k] = qs # Store all qs in one matrix

    
    # Compute the Quadratic Smooth Score (QS) = Tₙ(θ) = (1/n) ∑ᵢ ∑ₖ τₖ(xᵢ; θ) · qs(xᵢ, θₖ)
    # Compute the softmax weights with Softmax transformation --> τₖ(xᵢ; θ) = τₖ(xᵢ; θ) = exp(qs(xᵢ, θₖ)) / ∑ⱼ exp(qs(xᵢ, θⱼ))
    # Softmax ensures the scores are "probability like"
    max_qs = np.max(qs_matrix, axis=1, keepdims=True)  # For numerical stability, subtract the max per row
    exp_qs = np.exp(qs_matrix - max_qs)
    tau = exp_qs / exp_qs.sum(axis=1, keepdims=True)  # Softmax weights
    print("tau:",tau)

    # Compute  QS
    Tn = np.mean(np.sum(tau * qs_matrix, axis=1))
    print("QS:",Tn)

    # Keep track of skipped clusters because too cluster size <2              
    if len(labels.unique()) != int(re.search(r'k(\d+)', cluster_col).group(1)): 
            comments = f'k ≠ label'
    else: 
            comments = ""

    return Tn, tau, comments, cluster_size

"QS MATRIX INITIATED WITH ZEROS, however this affect the mean QS and the BQS"
"Cluster size check inside the loop" 

def compute_QS(data, byvar, cluster_col):
   
    n,p = data.shape  # Num_rows, Num_columns
    labels = data[cluster_col] # Cluster assignments
    k = len(labels.unique()) # Number of clusters

    print(f'\n Computing QS for {cluster_col}')

    # Extract parameters
    cluster_size = labels.value_counts().sort_index().values # Array of cluster sizes
    cluster_sizefraction = labels.value_counts().sort_index().values/n # Fraction of the sample belonging to each cluster
    cluster_centers = data[byvar + [cluster_col]].groupby(cluster_col).mean()  # Centroid vector
    print('cluster_size:', cluster_size)
    
    # Compute Quadratic Score qs
    X = data[byvar].to_numpy() #Convert psaid data to numpy array
    qs_matrix = np.full((n, k), np.nan)  # Reserve space for qs_matrix
    skipped_clusters = [] # Reserve space
    
    for k in sorted(labels.unique()):

        # Check for singular mixture components. If <2 the cov matrix is undefined/dof<=0 -->  If singular the $inv(Sigma_k)$ can not be computed because det(Sigma_k) = 0.
        if cluster_size[k]<2:
          #  print(f'Skipping cluster {k}, because size {cluster_size}<2 so kan not compute inv(Sigma_k)')
            skipped_clusters.append(k) # Log which clusters are skipped
            continue #skip remaining lines in the loop
        
        pi_k = cluster_sizefraction[k] # Fraction of cluster k
        mu_k = cluster_centers.loc[k].to_numpy() # Centers of cluster k

        # Compute scatter/covariance
        cluster_data = data.loc[labels == k, byvar]
        Sig_k = np.cov(cluster_data, rowvar=False, ddof=1) # Compute sample scatter = covariance matrix of cluster k

        # Check for linear dependencies --> Compute Rank of sample 
        # If the cov matrix is singular --> Ridge regularization to make invertible
        if np.linalg.matrix_rank(Sig_k) < len(byvar): 
            Sig_k += 1e-6 * np.eye(len(byvar))

        # Compute the quadratic term = 1/2 * (xᵢ - μₖ)ᵀ Σₖ⁻¹ (xᵢ - μₖ)
        diff = X - mu_k # Difference Vectors
        inv_Sig = np.linalg.inv(Sig_k) #Log DEeterminant
        quad = np.einsum('ij,jk,ik->i', diff, inv_Sig, diff) # Quadratic term = Mahalanobis distance squared # Einsum lets you define custom summation patterns

        # Compute Log Determinant of Sig_k
        # By using slogdet and ignoring sign, Sig_k is assumed positive-definite, which is usually fine if you regularize
        sign, logdet = np.linalg.slogdet(Sig_k)
 
        # Compute the Quadratice Scores for all observations in cluster k
        qs = np.log(pi_k)-0.5*logdet-0.5*quad
        qs_matrix[:,k] = qs # Store all qs in one matrix

    
    # Compute the Quadratic Smooth Score (QS) = Tₙ(θ) = (1/n) ∑ᵢ ∑ₖ τₖ(xᵢ; θ) · qs(xᵢ, θₖ)
    # Compute the softmax weights with Softmax transformation --> τₖ(xᵢ; θ) = τₖ(xᵢ; θ) = exp(qs(xᵢ, θₖ)) / ∑ⱼ exp(qs(xᵢ, θⱼ))
    # Softmax ensures the scores are "probability like"
    print("missing qs_columns", np.sum(np.isnan(qs_matrix)/n))
    mask = ~np.isnan(qs_matrix) # Mask the clusters where n < 2
    # qs_masked = np.where(mask, qs_matrix - max_qs, -np.inf)
    # print(qs_masked)
    max_qs = np.max(qs_matrix, axis=1, keepdims=True)  # For numerical stability, subtract the max per row
    exp_qs = np.exp(np.where(mask, qs_matrix - max_qs, -np.inf))
    tau = exp_qs / exp_qs.sum(axis=1, keepdims=True)

    #CODE BEFORE APPLYING MASK /* 
    # exp_qs = np.exp(qs_matrix - max_qs)
    # tau = exp_qs / exp_qs.sum(axis=1, keepdims=True)  # Softmax weights
    #*/

    # Compute  QS
    Tn = np.mean(np.sum(tau * qs_matrix, axis=1))
    Tn_nan = np.nanmean(np.nansum(tau * qs_matrix, axis=1))
    print("Tn:", Tn, "Tn_nan:", Tn_nan)

    # Keep track of skipped clusters because too cluster size <2
    if skipped_clusters:
        comments = f'skipped cluster {skipped_clusters}'
    else:
        comments = ""

    return Tn, tau, comments, cluster_size

In [33]:
## Computed with Unscaled data
cluster_columns = [i for i in dataset.columns if re.match(r'^clusterID_',i)]

QS = []
for cluster in cluster_columns:
    Tn, _, comments, cluster_size = compute_QS(dataset[columns_gp+[cluster]], columns_gp, cluster)
    QS.append({'K': cluster,'QS': Tn, 'QS_comment': comments, 'Cluster Size': cluster_size})

QS_df = pd.DataFrame(QS)

if save_results:
    #Mark dataset with computation date.time
    timestamp = datetime.now().strftime("%Y%m%d_%H:%M:%S")
    QS_df = pd.concat(QS_df, ignore_index=True)
    QS_df['timestamp'] = timestamp

    # Store
    file_name = f'PsAID_QS_{timestamp}'
    
    # Ensure the folder exists
    os.makedirs(data_storage, exist_ok=True)
    
    # Save
    QS_df.to_csv(f'{data_storage}/{file_name}.csv', index=False)
    print(f' Dataset saved to {data_storage}/{file_name}.csv')

QS_df

K:2

 Computing QS for clusterID_HACcomplete_k2
cluster_size: [ 383 4716]
tau: [[3.65789077e-13 1.00000000e+00]
 [2.92120447e-10 1.00000000e+00]
 [2.65072723e-01 7.34927277e-01]
 ...
 [9.99999991e-01 8.53705084e-09]
 [7.96488525e-01 2.03511475e-01]
 [5.89228296e-15 1.00000000e+00]]
QS: -11.368644875604362
K:3

 Computing QS for clusterID_HACcomplete_k3
cluster_size: [ 383 3697 1019]
tau: [[6.92539794e-14 9.99999964e-01 3.56690171e-08]
 [8.62267727e-11 9.99998340e-01 1.66027337e-06]
 [4.18020935e-02 2.53901825e-08 9.58197881e-01]
 ...
 [9.99999620e-01 1.46360549e-27 3.79971023e-07]
 [6.37631597e-01 3.39186428e-06 3.62365011e-01]
 [2.05979870e-15 9.99981440e-01 1.85600981e-05]]
QS: -10.384874190785968
K:4

 Computing QS for clusterID_HACcomplete_k4
cluster_size: [ 383 3697  179  840]
tau: [[6.92539769e-14 9.99999927e-01 4.18799910e-17 7.25739850e-08]
 [8.62267427e-11 9.99997992e-01 4.94569980e-13 2.00823675e-06]
 [4.06608220e-02 2.46969854e-08 4.20013783e-01 5.39325370e-01]
 ...
 [1.00000000e+00 1.46360604e-27 2.47879075e-13 6.54713960e-11]
 [7.01280635e-01 3.73044364e-06 3.07830002e-02 2.67932634e-01]
 [2.05979370e-15 9.99979016e-01 1.36247931e-14 2.09836835e-05]]
QS: -10.40164627581556
K:5

 Computing QS for clusterID_HACcomplete_k5
cluster_size: [ 383 3697  179   87  753]
tau: [[6.92539743e-14 9.99999890e-01 4.18799895e-17 2.25714524e-24
  1.09781654e-07]
 [8.62267226e-11 9.99997759e-01 4.94569865e-13 2.49250235e-16
  2.24103362e-06]
 [5.22346829e-02 3.17268352e-08 5.39568206e-01 4.55464629e-03
  4.03642433e-01]
 ...
 [1.00000000e+00 1.46360604e-27 2.47879075e-13 3.71927939e-22
  8.88810931e-11]
 [7.08542867e-01 3.76907488e-06 3.11017789e-02 1.36135310e-03
  2.58990232e-01]
 [2.05976244e-15 9.99963840e-01 1.36245863e-14 1.94317024e-20
  3.61604860e-05]]
QS: -10.402623076067778
K:7

 Computing QS for clusterID_HACcomplete_k7
cluster_size: [ 383  673 2420  604  179   87  753]
tau: [[1.15585548e-14 4.90654450e-04 9.97803272e-01 ... 6.98981046e-18
  3.76719708e-25 1.83226635e-08]
 [1.56234914e-10 3.87309333e-01 6.03088864e-01 ... 8.96115241e-13
  4.51618569e-16 4.06054741e-06]
 [5.22340236e-02 1.26478410e-05 3.58968805e-20 ... 5.39561395e-01
  4.55458880e-03 4.03637338e-01]
 ...
 [1.00000000e+00 7.61539448e-22 1.49368903e-84 ... 2.47879075e-13
  3.71927939e-22 8.88810931e-11]
 [7.08501449e-01 5.79012054e-05 4.28576326e-16 ... 3.10999608e-02
  1.36127352e-03 2.58975093e-01]
 [1.74769985e-15 9.54363158e-01 4.20487137e-02 ... 1.15604047e-14
  1.64877185e-20 3.06820217e-05]]
QS: -9.318363624004085

,K,QS,QS_comment,Cluster Size
0,clusterID_HACcomplete_k2,-11.368645,,"[383, 4716]"
1,clusterID_HACcomplete_k3,-10.384874,,"[383, 3697, 1019]"
2,clusterID_HACcomplete_k4,-10.401646,,"[383, 3697, 179, 840]"
3,clusterID_HACcomplete_k5,-10.402623,,"[383, 3697, 179, 87, 753]"
4,clusterID_HACcomplete_k7,-9.318364,,"[383, 673, 2420, 604, 179, 87, 753]"

# Compute BQS
Algorithm 2 - page 10 + Supplement S5

**Compute BQS**

1. Bootstrap sampling ($b$=1000) <br>
   This method involves randomly sampling with replacement from the original dataset to create multiple smaller samples. It is commonly used to estimate the distribution of a statistic. One of its most common uses is to estimate confidence intervals when the underlying distribution is unknown or when sample sizes are small.
   - Classical Efrons non-parametric bootstrap idea (use case: Estimating the variability of statistics like the mean, median, regression coefficients)
   - Use 1000 bootstraps for real datasets

2. Compute clusters with each bootstrap sample ($\theta^{b}$)

3. Compute the quadratic score as explained previously ($S^{b}$ = sample_QS)

4. Compute the mean quadratic score over all $b$ ($W_{n}$)

5. Standardize $W_{n}$ ($R_{n}$)

6. Compute the 95% CI ($L_{n}$, $U_{n}$)

**Select the best clutering solution:** <br> 
Rather than selecting cluster configurations achieving the largest estimated W. We propose to select BQS = argmax($L_{n}$).

In [34]:
def compute_ARI(OG_data, sample_data, byvar, cluster_col):
    OG_labels = OG_data[cluster_col] # Reference cluster assignments
    X_OG = OG_data[byvar].to_numpy()
    OG_n = OG_data.shape[0]
    sample_n = sample_data.shape[0]

    # Extract bootstrap cluster descriptions
    sample_labels = sample_data[cluster_col] # Cluster assignments
    k = len(sample_labels.unique()) # Number of clusters
    cluster_centers = sample_data[byvar + [cluster_col]].groupby(cluster_col).mean()  # Centroid vector
    cluster_size = sample_labels.value_counts().sort_index().values # Array of cluster sizes
    print("cluster_size:", cluster_size)
    cluster_sizefraction = sample_labels.value_counts().sort_index().values/sample_n # Fraction of the sample belonging to each cluster

    # ---- validity check ----
    # Check for singular mixture components. If <2 the cov matrix is undefined/dof<=0 -->  If singular the $inv(Sigma_k)$ can not be computed because det(Sigma_k) = 0.
    # Thus can't calculate tau
    if np.any(cluster_size <2):
        sample_ARI = np.nan
        return sample_ARI

    # Reserve storage space
    qs_matrix = np.full((OG_n, k), np.nan)
   # qs_matrix = np.zeros((OG_n, k))
   # print("qs matrix:", np.shape(qs_matrix))
    
    # Probabilites of original data belonging to bootstrap cluster k
    for k in sorted(sample_labels.unique()):

        cluster_data = sample_data.loc[sample_labels == k, byvar]
        
        # Compute scatter/covariance
        Sig_k = np.cov(cluster_data, rowvar=False, ddof=1) # Compute sample scatter = covariance matrix of cluster k
        if np.linalg.matrix_rank(Sig_k) < len(byvar): # If not full rank
            Sig_k += 1e-6 * np.eye(len(byvar))        # Ridge Regularization

        mu_k = cluster_centers.loc[k].to_numpy() # Centers of cluster k
        pi_k = cluster_sizefraction[k] # Cluster size fraction

        # Compute the quadratic term = 1/2 * (xᵢ - μₖ)ᵀ Σₖ⁻¹ (xᵢ - μₖ)
        diff = X_OG - mu_k # Difference Vectors
        inv_Sig = np.linalg.inv(Sig_k) #Log DEeterminant
        quad = np.einsum('ij,jk,ik->i', diff, inv_Sig, diff) # Quadratic term = Mahalanobis distance squared # Einsum lets you define custom summation patterns

        # Compute Log Determinant of Sig_k
        # By using slogdet and ignoring sign, Sig_k is assumed positive-definite, which is usually fine if you regularize
        sign, logdet = np.linalg.slogdet(Sig_k)
 
        # Compute the Quadratice Scores for all observations in cluster k
        qs = np.log(pi_k)-0.5*logdet-0.5*quad
        qs_matrix[:,k] = qs # Store all qs in one matrix

    # Softmax transformation to ensure scores are 'probability like'
    max_qs = np.max(qs_matrix, axis=1, keepdims=True)  # For numerical stability, subtract the max per row
    exp_qs = np.exp(qs_matrix - max_qs)
    tau = exp_qs / exp_qs.sum(axis=1, keepdims=True)  # Softmax weights = probabilities

    # Assign OG_data to the most likely bootstrap cluster
    projected_labels = tau.argmax(axis=1)

    # Compute Ari against original labels
    sample_ARI = adjusted_rand_score(OG_labels, projected_labels)

    return sample_ARI

In [35]:
def bootstrap_iteration(b, data, byvar, algorithm, s, randomstate):
    import os, logging
    logging.basicConfig(
        filename='debug_BQS.log',
        filemode='a',
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        force=True
    )
    
    n = data.shape[0]
    OG_data = data.copy()

    # Sample with replacement
    sample_idx = np.random.choice(n, n, replace=True)
    sample_data = data.iloc[sample_idx].reset_index(drop=True)

    # Run clustering
    if algorithm == 'kmeans':
        n_clusters = s
        sample_data, clusterID = kmeans_clustering(sample_data, n_clusters, randomstate, byvar)

    elif algorithm == 'HAC_ward':
            n_clusters = s
            sample_data, clusterID = HAC_ward_clustering(sample_data, n_clusters)
            logging.info(f"{algorithm}_{s}, b:{b}, computed_k: {len(np.unique(sample_data[clusterID]))}")

    elif algorithm == 'Spectral_Density':
        setting = s
        sample_data, clusterID = run_spectral_clustering(sample_data, setting, byvar, randomstate)

    else:
        raise ValueError(f"Unknown algorithm: {algorithm}")

    # Compute sample QS
    sample_QS, sample_tau, sample_comment, _ = suppress_print(compute_QS, sample_data, byvar, clusterID)
    # Turn on prints for debugging
    #print('computing QS')
    #sample_QS, sample_tau, sample_comment = compute_QS(sample_data, byvar, clusterID)  # For debugging

    # Compute ARI
    sample_ARI = suppress_print(compute_ARI, OG_data[byvar+[clusterID]], sample_data[byvar+[clusterID]], byvar, clusterID)
    # Turn on prints for debugging
    # Turn on prints for debugging
    #sample_ARI = compute_ARI(OG_data[byvar+[clusterID]], sample_data[byvar+[clusterID]], byvar, clusterID)

    return sample_QS, sample_comment, clusterID, sample_ARI

for b in range(1,10): 
    print("b:", b)
    n = dataset.shape[0]
    sample_idx = np.random.choice(n, n, replace=True)
    sample_data = dataset.iloc[sample_idx].reset_index(drop=True)

    # HAC_ward
    sample_QS, sample_comment, clusterID, sample_ARI =bootstrap_iteration(b, sample_data, columns_gp, 'HAC_ward', s = 5, randomstate=RandomSeed) 
    
# Spectral Density 
#    sample_QS, sample_comment, clusterID, sample_ARI =bootstrap_iteration(b, sample_data, columns_gp, 'Spectral_Density', s = spectral_settings['run_K4A'], randomstate=RandomSeed) 
    
    print(sample_QS)
    print(sample_ARI)
    print(sample_comment)

In [36]:
def compute_BQS_ARI_inParallel(data, byvar, algorithm, s, n_bootstrap=1000, randomstate=RandomSeed, n_jobs=-1):
    start = time.time()
    
    # Run bootstraps in parallel
    results = Parallel(n_jobs=n_jobs, backend="loky", verbose=5)(  #For debuggin use backend = threading", otherwise "loky" to suppress prints
        delayed(bootstrap_iteration)(b, data, byvar, algorithm, s, randomstate)
        for b in range(n_bootstrap)
    )
    
    # Unpack results
    qs_list, comment_list, clusterIDs, ARI_list = zip(*results)
    clusterID = clusterIDs[-1]  # use last clusterID (same as before)

    qs_array = np.array(qs_list) # Convert list to numpy array
  
    # ---- validity check ----
    # If +> 25% of the runs are invalid, discard the discard method.
    n_nan = np.sum(np.isnan(qs_array))  # Count missing sample_qs values
    # n_nonempty_c = sum([1 for c in comment_list if c.strip() != ""])  # based on  comments 
    proportion_empty = n_nan / n_bootstrap * 100   # Convert # missing values to %
    if proportion_empty > 24: 
        BQS = np.nan
        results_dict = {
            'K': clusterID,
            'ARI': np.nan,
            'QS_mean': np.nan,
            'L_ci': np.nan,
            'U_ci': np.nan,
            # 'all_QS': qs_array,
            '%-discarded': proportion_empty,
            'duration': np.nan,
            'b': n_bootstraps
        }
        return clusterID, BQS, results_dict

    # Verify for HAC how many times the clusterID does not match the #clusters computed
    logging.info(comment_list)
    label_k_mismatch_pattern = r'k\s*≠\s*label'
    label_k_mismatch = sum(bool(re.search(label_k_mismatch_pattern, c)) for c in comment_list)
    proportion_mismatch = label_k_mismatch / n_bootstrap * 100   # Convert # mismatches to % 
    logging.info(f'{algorithm}_{s} - b: {n_bootstrap} | #_mismatches: {label_k_mismatch}| proportion_mismatch: {proportion_mismatch}')
        
    # Compute BQS
    qs_valid = qs_array[~np.isnan(qs_array)]
    W = qs_valid.mean()
    R = np.sqrt(data.shape[0]) * (qs_valid - W)
    alpha = 0.05
    L = np.quantile(R, alpha/2) 
    U = np.quantile(R, 1 - alpha/2)

    BQS = L

    # Average ARI
    ARI_array = np.array(ARI_list)
    ARI_mean = np.nanmean(ARI_array)

    results_dict = {
        'K': clusterID,
        'ARI': ARI_mean,
        'QS_mean': W,
        'L_ci': L,
        'U_ci': U,
       # 'all_QS': qs_array,
        '%-discarded': proportion_empty,
        '%-mismatch':proportion_mismatch,
        'duration': f'{time.time()-start:.2f}s',
        'b': n_bootstrap
    }

    print(pd.DataFrame([results_dict])[['K', 'ARI', 'QS_mean', 'L_ci', 'U_ci', '%-discarded', '%-mismatch', 'duration']])

    return clusterID, round(BQS,5), results_dict

In [37]:
BQS = []
bqs_list = []

for algorithm in algorithms:
    if algorithm == 'kmeans':
        for n_clust in range(2,10):
            clusterID, qs_bootstrapped, bqs_results = compute_BQS_ARI_inParallel(dataset, columns_gp, algorithm, s = n_clust)
            BQS.append({'K': clusterID, 'BQS':qs_bootstrapped})
            bqs_list.append(pd.DataFrame([bqs_results])[['K', 'ARI', 'QS_mean', 'L_ci', 'U_ci', '%-discarded', '%-mismatch', 'duration', 'b']])
    
    if algorithm == 'HAC_ward':
            for n_clust in [2,3,4, 5,7]:
                clusterID, qs_bootstrapped, bqs_results= compute_BQS_ARI_inParallel(dataset, columns_gp, algorithm, s = n_clust)
                BQS.append({'K': clusterID, 'BQS':qs_bootstrapped})
                bqs_list.append(pd.DataFrame([bqs_results])[['K', 'ARI', 'QS_mean', 'L_ci', 'U_ci', '%-discarded', '%-mismatch', 'duration', 'b']])

    if algorithm == 'Spectral_Density': 
        for sett in spectral_settings:
            clusterID, qs_bootstrapped, bqs_results = compute_BQS_ARI_inParallel(dataset, columns_gp, algorithm, s = spectral_settings[sett])
            BQS.append({'K': clusterID, 'BQS':qs_bootstrapped})
            bqs_list.append(pd.DataFrame([bqs_results])[['K', 'ARI', 'QS_mean', 'L_ci', 'U_ci', '%-discarded', '%-mismatch', 'duration', 'b']])

os.system('say "BQS Computed!"')
print('Done computing BQS')
BQS_df = pd.concat(bqs_list, ignore_index=True)

if save_results: 
    #Mark dataset with computation date.time
    timestamp = datetime.now().strftime("%Y%m%d_%H:%M:%S")
    BQS_df = pd.concat(bqs_list, ignore_index=True)
    BQS_df['timestamp'] = timestamp
    
    # Store
    file_name = f'PsAID_BQS_{timestamp}'
    
    # Ensure the folder exists
    os.makedirs(data_storage, exist_ok=True)
    
    # Save
    BQS_df.to_csv(f'{data_storage}/{file_name}.csv', index=False)
    print(f' Dataset saved to {data_storage}/{file_name}.csv')

BQS_df

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    4.2s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:   12.4s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   28.1s
[Parallel(n_jobs=-1)]: Done 272 tasks      | elapsed:   48.8s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-1)]: Done 866 tasks      | elapsed: 15.1min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed: 15.5min finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.

                          K       ARI   QS_mean       L_ci       U_ci  \
0  clusterID_HACcomplete_k2  0.439034 -10.99546 -33.953417  44.759848

   %-discarded  %-mismatch duration
0          0.0         0.0  927.36s

[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    1.4s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:   10.2s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   25.7s
[Parallel(n_jobs=-1)]: Done 272 tasks      | elapsed:   46.1s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-1)]: Done 866 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:  2.8min finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.

                          K       ARI    QS_mean       L_ci       U_ci  \
0  clusterID_HACcomplete_k3  0.653186 -10.428633 -39.732411  49.786513

   %-discarded  %-mismatch duration
0          0.0         0.1  168.42s

[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    1.4s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    9.6s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   25.7s
[Parallel(n_jobs=-1)]: Done 272 tasks      | elapsed:   47.3s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-1)]: Done 866 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed: 36.6min finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.

                          K       ARI    QS_mean       L_ci       U_ci  \
0  clusterID_HACcomplete_k4  0.631826 -10.206347 -38.558203  47.642731

   %-discarded  %-mismatch  duration
0          0.0         0.4  2194.70s

[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    1.5s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:   10.7s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   29.3s
[Parallel(n_jobs=-1)]: Done 272 tasks      | elapsed:   54.5s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:  1.5min

k:2
sizes: [4013 1086]
clusterID_HACcomplete_k2
k:2
sizes: [ 411 4688]
clusterID_HACcomplete_k2
k:2
sizes: [ 580 4519]
clusterID_HACcomplete_k2
k:2
sizes: [ 456 4643]
clusterID_HACcomplete_k2
k:2
sizes: [ 539 4560]
clusterID_HACcomplete_k2
k:2
sizes: [ 482 4617]
clusterID_HACcomplete_k2
k:2
sizes: [ 413 4686]
clusterID_HACcomplete_k2
k:2
sizes: [4040 1059]
clusterID_HACcomplete_k2
k:2
sizes: [ 367 4732]
clusterID_HACcomplete_k2
k:2
sizes: [1283 3816]
clusterID_HACcomplete_k2
k:2
sizes: [3864 1235]
clusterID_HACcomplete_k2
k:2
sizes: [ 580 4519]
clusterID_HACcomplete_k2
k:2
sizes: [ 343 4756]
clusterID_HACcomplete_k2
k:2
sizes: [3682 1417]
clusterID_HACcomplete_k2
k:2
sizes: [ 415 4684]
clusterID_HACcomplete_k2
k:2
sizes: [ 567 4532]
clusterID_HACcomplete_k2
k:2
sizes: [3522 1577]
clusterID_HACcomplete_k2
k:2
sizes: [4230  869]
clusterID_HACcomplete_k2
k:2
sizes: [3953 1146]
clusterID_HACcomplete_k2
k:2
sizes: [ 257 4842]
clusterID_HACcomplete_k2
k:2
sizes: [3673 1426]
clusterID_HACcomplete_k2
k:2
sizes: [4065 1034]
clusterID_HACcomplete_k2
k:2
sizes: [ 454 4645]
clusterID_HACcomplete_k2
k:2
sizes: [4153  946]
clusterID_HACcomplete_k2
k:2
sizes: [4033 1066]
clusterID_HACcomplete_k2
k:2
sizes: [4157  942]
clusterID_HACcomplete_k2
k:2
sizes: [ 361 4738]
clusterID_HACcomplete_k2
k:2
sizes: [4188  911]
clusterID_HACcomplete_k2
k:2
sizes: [4027 1072]
clusterID_HACcomplete_k2
k:2
sizes: [3872 1227]
clusterID_HACcomplete_k2
k:2
sizes: [3907 1192]
clusterID_HACcomplete_k2
k:2
sizes: [3945 1154]
clusterID_HACcomplete_k2
k:2
sizes: [ 680 4419]
clusterID_HACcomplete_k2
k:2
sizes: [ 442 4657]
clusterID_HACcomplete_k2
k:2
sizes: [ 403 4696]
clusterID_HACcomplete_k2
k:2
sizes: [ 555 4544]
clusterID_HACcomplete_k2
k:2
sizes: [ 376 4723]
clusterID_HACcomplete_k2
k:2
sizes: [ 695 4404]
clusterID_HACcomplete_k2
k:2
sizes: [ 776 4323]
clusterID_HACcomplete_k2
k:2
sizes: [ 546 4553]
clusterID_HACcomplete_k2
k:2
sizes: [ 338 4761]
clusterID_HACcomplete_k2
k:2
sizes: [4200  899]
clusterID_HACcomplete_k2
k:2
sizes: [3982 1117]
clusterID_HACcomplete_k2
k:2
sizes: [4071 1028]
clusterID_HACcomplete_k2
k:2
sizes: [ 489 4610]
clusterID_HACcomplete_k2
k:2
sizes: [3998 1101]
clusterID_HACcomplete_k2
k:2
sizes: [ 344 4755]
clusterID_HACcomplete_k2
k:2
sizes: [3795 1304]
clusterID_HACcomplete_k2
k:2
sizes: [ 704 4395]
clusterID_HACcomplete_k2
k:2
sizes: [4109  990]
clusterID_HACcomplete_k2
k:2
sizes: [4012 1087]
clusterID_HACcomplete_k2
k:2
sizes: [3820 1279]
clusterID_HACcomplete_k2
k:2
sizes: [ 357 4742]
clusterID_HACcomplete_k2
k:2
sizes: [4501  598]
clusterID_HACcomplete_k2
k:2
sizes: [3790 1309]
clusterID_HACcomplete_k2
k:2
sizes: [ 323 4776]
clusterID_HACcomplete_k2
k:2
sizes: [ 228 4871]
clusterID_HACcomplete_k2
k:2
sizes: [1022 4077]
clusterID_HACcomplete_k2
k:2
sizes: [3582 1517]
clusterID_HACcomplete_k2
k:2
sizes: [3644 1455]
clusterID_HACcomplete_k2
k:2
sizes: [ 755 4344]
clusterID_HACcomplete_k2
k:2
sizes: [4007 1092]
clusterID_HACcomplete_k2
k:2
sizes: [ 530 4569]
clusterID_HACcomplete_k2
k:2
sizes: [ 267 4832]
clusterID_HACcomplete_k2
k:2
sizes: [3589 1510]
clusterID_HACcomplete_k2
k:2
sizes: [3828 1271]
clusterID_HACcomplete_k2
k:2
sizes: [4173  926]
clusterID_HACcomplete_k2
k:2
sizes: [ 416 4683]
clusterID_HACcomplete_k2
k:2
sizes: [ 553 4546]
clusterID_HACcomplete_k2
k:2
sizes: [ 802 4297]
clusterID_HACcomplete_k2
k:2
sizes: [3443 1656]
clusterID_HACcomplete_k2
k:2
sizes: [4286  813]
clusterID_HACcomplete_k2
k:2
sizes: [ 813 4286]
clusterID_HACcomplete_k2
k:2
sizes: [3921 1178]
clusterID_HACcomplete_k2
k:2
sizes: [ 425 4674]
clusterID_HACcomplete_k2
k:2
sizes: [ 548 4551]
clusterID_HACcomplete_k2
k:2
sizes: [ 420 4679]
clusterID_HACcomplete_k2
k:2
sizes: [3973 1126]
clusterID_HACcomplete_k2
k:2
sizes: [ 897 4202]
clusterID_HACcomplete_k2
k:2
sizes: [4136  963]
clusterID_HACcomplete_k2
k:2
sizes: [4311  788]
clusterID_HACcomplete_k2
k:2
sizes: [ 394 4705]
clusterID_HACcomplete_k2
k:2
sizes: [3777 1322]
clusterID_HACcomplete_k2
k:2
sizes: [ 620 4479]
clusterID_HACcomplete_k2
k:2
sizes: [ 565 4534]
clusterID_HACcomplete_k2
k:2
sizes: [ 578 4521]
clusterID_HACcomplete_k2
k:2
sizes: [4195  904]
clusterID_HACcomplete_k2
k:2
sizes: [ 338 4761]
clusterID_HACcomplete_k2
k:2
sizes: [4077 1022]
clusterID_HACcomplete_k2
k:2
sizes: [3812 1287]
clusterID_HACcomplete_k2
k:2
sizes: [ 326 4773]
clusterID_HACcomplete_k2
k:2
sizes: [ 295 4804]
clusterID_HACcomplete_k2
k:2
sizes: [ 398 4701]
clusterID_HACcomplete_k2
k:2
sizes: [ 444 4655]
clusterID_HACcomplete_k2
k:2
sizes: [ 350 4749]
clusterID_HACcomplete_k2
k:2
sizes: [3931 1168]
clusterID_HACcomplete_k2
k:2
sizes: [ 545 4554]
clusterID_HACcomplete_k2
k:2
sizes: [ 595 4504]
clusterID_HACcomplete_k2
k:2
sizes: [ 449 4650]
clusterID_HACcomplete_k2
k:2
sizes: [ 516 4583]
clusterID_HACcomplete_k2
k:2
sizes: [3892 1207]
clusterID_HACcomplete_k2
k:2
sizes: [ 337 4762]
clusterID_HACcomplete_k2
k:2
sizes: [3780 1319]
clusterID_HACcomplete_k2
k:2
sizes: [3813 1286]
clusterID_HACcomplete_k2
k:2
sizes: [3887 1212]
clusterID_HACcomplete_k2
k:2
sizes: [ 252 4847]
clusterID_HACcomplete_k2
k:2
sizes: [ 541 4558]
clusterID_HACcomplete_k2
k:2
sizes: [ 308 4791]
clusterID_HACcomplete_k2
k:2
sizes: [3680 1419]
clusterID_HACcomplete_k2
k:2
sizes: [ 501 4598]
clusterID_HACcomplete_k2
k:2
sizes: [ 920 4179]
clusterID_HACcomplete_k2
k:2
sizes: [3984 1115]
clusterID_HACcomplete_k2
k:2
sizes: [ 395 4704]
clusterID_HACcomplete_k2
k:2
sizes: [ 773 4326]
clusterID_HACcomplete_k2
k:2
sizes: [ 180 4919]
clusterID_HACcomplete_k2
k:2
sizes: [3953 1146]
clusterID_HACcomplete_k2
k:2
sizes: [3920 1179]
clusterID_HACcomplete_k2
k:2
sizes: [ 567 4532]
clusterID_HACcomplete_k2
k:2
sizes: [4225  874]
clusterID_HACcomplete_k2
k:2
sizes: [ 576 4523]
clusterID_HACcomplete_k2
k:2
sizes: [4070 1029]
clusterID_HACcomplete_k2
k:2
sizes: [3957 1142]
clusterID_HACcomplete_k2
k:2
sizes: [ 434 4665]
clusterID_HACcomplete_k2
k:2
sizes: [ 477 4622]
clusterID_HACcomplete_k2
k:2
sizes: [3876 1223]
clusterID_HACcomplete_k2
k:3
sizes: [ 787  803 3509]
clusterID_HACcomplete_k3
k:3
sizes: [4268  452  379]
clusterID_HACcomplete_k3
k:3
sizes: [ 669 3035 1395]
clusterID_HACcomplete_k3
k:3
sizes: [ 487 3469 1143]
clusterID_HACcomplete_k3
k:3
sizes: [3840  364  895]
clusterID_HACcomplete_k3
k:3
sizes: [3690  283 1126]
clusterID_HACcomplete_k3
k:3
sizes: [ 462 2975 1662]
clusterID_HACcomplete_k3
k:3
sizes: [ 589 3464 1046]
clusterID_HACcomplete_k3
k:3
sizes: [ 454 3579 1066]
clusterID_HACcomplete_k3
k:3
sizes: [4183  269  647]
clusterID_HACcomplete_k3
k:3
sizes: [ 290 1177 3632]
clusterID_HACcomplete_k3
k:3
sizes: [ 740  895 3464]
clusterID_HACcomplete_k3
k:3
sizes: [4105  200  794]
clusterID_HACcomplete_k3
k:3
sizes: [3725   79 1295]
clusterID_HACcomplete_k3
k:3
sizes: [ 740 3686  673]
clusterID_HACcomplete_k3
k:3
sizes: [ 776 1141 3182]
clusterID_HACcomplete_k3
k:3
sizes: [ 485  799 3815]
clusterID_HACcomplete_k3
k:3
sizes: [3852  190 1057]
clusterID_HACcomplete_k3
k:3
sizes: [4016  229  854]
clusterID_HACcomplete_k3
k:3
sizes: [3760  185 1154]
clusterID_HACcomplete_k3
k:3
sizes: [3923  696  480]
clusterID_HACcomplete_k3
k:3
sizes: [3684  317 1098]
clusterID_HACcomplete_k3
k:3
sizes: [ 531  885 3683]
clusterID_HACcomplete_k3
k:3
sizes: [4165  455  479]
clusterID_HACcomplete_k3
k:3
sizes: [ 534 3276 1289]
clusterID_HACcomplete_k3
k:3
sizes: [3619  234 1246]
clusterID_HACcomplete_k3
k:3
sizes: [ 474 3515 1110]
clusterID_HACcomplete_k3
k:3
sizes: [ 501 3337 1261]
clusterID_HACcomplete_k3
k:3
sizes: [ 365 3344 1390]
clusterID_HACcomplete_k3
k:3
sizes: [ 860 3565  674]
clusterID_HACcomplete_k3
k:3
sizes: [ 584  790 3725]
clusterID_HACcomplete_k3
k:3
sizes: [ 285 3260 1554]
clusterID_HACcomplete_k3
k:3
sizes: [ 984  845 3270]
clusterID_HACcomplete_k3
k:3
sizes: [ 268 3916  915]
clusterID_HACcomplete_k3
k:3
sizes: [ 330 3520 1249]
clusterID_HACcomplete_k3
k:3
sizes: [4297  263  539]
clusterID_HACcomplete_k3
k:3
sizes: [ 450 3916  733]
clusterID_HACcomplete_k3
k:3
sizes: [ 301 3396 1402]
clusterID_HACcomplete_k3
k:3
sizes: [3992  244  863]
clusterID_HACcomplete_k3
k:3
sizes: [ 735  604 3760]
clusterID_HACcomplete_k3
k:3
sizes: [ 900  757 3442]
clusterID_HACcomplete_k3
k:3
sizes: [ 158 3321 1620]
clusterID_HACcomplete_k3
k:3
sizes: [ 783 1171 3145]
clusterID_HACcomplete_k3
k:3
sizes: [3927  288  884]
clusterID_HACcomplete_k3
k:3
sizes: [3943  294  862]
clusterID_HACcomplete_k3
k:3
sizes: [ 954  535 3610]
clusterID_HACcomplete_k3
k:3
sizes: [4183  235  681]
clusterID_HACcomplete_k3
k:3
sizes: [4186  556  357]
clusterID_HACcomplete_k3
k:3
sizes: [4006  669  424]
clusterID_HACcomplete_k3
k:3
sizes: [ 737 3454  908]
clusterID_HACcomplete_k3
k:3
sizes: [ 985  662 3452]
clusterID_HACcomplete_k3
k:3
sizes: [3923   62 1114]
clusterID_HACcomplete_k3
k:3
sizes: [ 407  979 3713]
clusterID_HACcomplete_k3
k:3
sizes: [4245  178  676]
clusterID_HACcomplete_k3
k:3
sizes: [ 755 1455 2889]
clusterID_HACcomplete_k3
k:3
sizes: [3641   85 1373]
clusterID_HACcomplete_k3
k:3
sizes: [ 349 3055 1695]
clusterID_HACcomplete_k3
k:3
sizes: [4316  299  484]
clusterID_HACcomplete_k3
k:3
sizes: [3707  253 1139]
clusterID_HACcomplete_k3
k:3
sizes: [ 259 3769 1071]
clusterID_HACcomplete_k3
k:3
sizes: [3801  283 1015]
clusterID_HACcomplete_k3
k:3
sizes: [ 565  818 3716]
clusterID_HACcomplete_k3
k:3
sizes: [3828  405  866]
clusterID_HACcomplete_k3
k:3
sizes: [ 773 3083 1243]
clusterID_HACcomplete_k3
k:3
sizes: [ 539  890 3670]
clusterID_HACcomplete_k3
k:3
sizes: [4155  157  787]
clusterID_HACcomplete_k3
k:3
sizes: [4054  135  910]
clusterID_HACcomplete_k3
k:3
sizes: [ 666 2941 1492]
clusterID_HACcomplete_k3
k:3
sizes: [ 426 1004 3669]
clusterID_HACcomplete_k3
k:3
sizes: [4116  193  790]
clusterID_HACcomplete_k3
k:3
sizes: [4473  212  414]
clusterID_HACcomplete_k3
k:3
sizes: [ 360 3473 1266]
clusterID_HACcomplete_k3
k:3
sizes: [ 537 3496 1066]
clusterID_HACcomplete_k3
k:3
sizes: [3896  151 1052]
clusterID_HACcomplete_k3
k:3
sizes: [4045  674  380]
clusterID_HACcomplete_k3
k:3
sizes: [ 365  712 4022]
clusterID_HACcomplete_k3
k:3
sizes: [ 540 1367 3192]
clusterID_HACcomplete_k3
k:3
sizes: [ 608 3498  993]
clusterID_HACcomplete_k3
k:3
sizes: [3826  681  592]
clusterID_HACcomplete_k3
k:3
sizes: [ 634 2684 1781]
clusterID_HACcomplete_k3
k:3
sizes: [ 557  967 3575]
clusterID_HACcomplete_k3
k:3
sizes: [ 549 3249 1301]
clusterID_HACcomplete_k3
k:3
sizes: [3771  295 1033]
clusterID_HACcomplete_k3
k:3
sizes: [3999  104  996]
clusterID_HACcomplete_k3
k:3
sizes: [4092  264  743]
clusterID_HACcomplete_k3
k:3
sizes: [ 451 3481 1167]
clusterID_HACcomplete_k3
k:3
sizes: [4180  353  566]
clusterID_HACcomplete_k3
k:3
sizes: [ 203 3293 1603]
clusterID_HACcomplete_k3
k:3
sizes: [ 538 3267 1294]
clusterID_HACcomplete_k3
k:3
sizes: [3954  383  762]
clusterID_HACcomplete_k3
k:3
sizes: [3656  322 1121]
clusterID_HACcomplete_k3
k:3
sizes: [4197  151  751]
clusterID_HACcomplete_k3
k:3
sizes: [4135  331  633]
clusterID_HACcomplete_k3
k:3
sizes: [3911  336  852]
clusterID_HACcomplete_k3
k:3
sizes: [3826  100 1173]
clusterID_HACcomplete_k3
k:3
sizes: [ 408  715 3976]
clusterID_HACcomplete_k3
k:3
sizes: [ 391 3298 1410]
clusterID_HACcomplete_k3
k:3
sizes: [4176  200  723]
clusterID_HACcomplete_k3
k:3
sizes: [ 288 3290 1521]
clusterID_HACcomplete_k3
k:3
sizes: [4156  171  772]
clusterID_HACcomplete_k3
k:3
sizes: [ 632  645 3822]
clusterID_HACcomplete_k3
k:3
sizes: [ 513 3370 1216]
clusterID_HACcomplete_k3
k:3
sizes: [ 630 3557  912]
clusterID_HACcomplete_k3
k:3
sizes: [3803  402  894]
clusterID_HACcomplete_k3
k:3
sizes: [ 270 3847  982]
clusterID_HACcomplete_k3
k:3
sizes: [ 423 3758  918]
clusterID_HACcomplete_k3
k:3
sizes: [3895  149 1055]
clusterID_HACcomplete_k3
k:3
sizes: [ 884 2973 1242]
clusterID_HACcomplete_k3
k:3
sizes: [ 469 3457 1173]
clusterID_HACcomplete_k3
k:3
sizes: [3705  295 1099]
clusterID_HACcomplete_k3
k:3
sizes: [ 243 3317 1539]
clusterID_HACcomplete_k3
k:3
sizes: [ 716 3616  767]
clusterID_HACcomplete_k3
k:3
sizes: [4134  222  743]
clusterID_HACcomplete_k3
k:3
sizes: [ 327 3622 1150]
clusterID_HACcomplete_k3
k:3
sizes: [4221  383  495]
clusterID_HACcomplete_k3
k:3
sizes: [ 548 1419 3132]
clusterID_HACcomplete_k3
k:3
sizes: [ 293 3487 1319]
clusterID_HACcomplete_k3
k:3
sizes: [3716  461  922]
clusterID_HACcomplete_k3
k:3
sizes: [ 787 1324 2988]
clusterID_HACcomplete_k3
k:3
sizes: [3731  272 1096]
clusterID_HACcomplete_k3
k:3
sizes: [ 305 3870  924]
clusterID_HACcomplete_k3
k:3
sizes: [ 166 3682 1251]
clusterID_HACcomplete_k3
k:3
sizes: [ 175 2995 1929]
clusterID_HACcomplete_k3
k:3
sizes: [ 497 2939 1663]
clusterID_HACcomplete_k3
k:3
sizes: [ 419 3387 1293]
clusterID_HACcomplete_k3
k:4
sizes: [ 344 3299  484  972]
clusterID_HACcomplete_k4
k:4
sizes: [ 568  382 3200  949]
clusterID_HACcomplete_k4
k:4
sizes: [ 353  548  396 3802]
clusterID_HACcomplete_k4
k:4
sizes: [4011  199  256  633]
clusterID_HACcomplete_k4
k:4
sizes: [ 198  431 3062 1408]
clusterID_HACcomplete_k4
k:4
sizes: [ 339 3590  744  426]
clusterID_HACcomplete_k4
k:4
sizes: [ 239  253 1175 3432]
clusterID_HACcomplete_k4
k:4
sizes: [3285  816  689  309]
clusterID_HACcomplete_k4
k:4
sizes: [3811  417  615  256]
clusterID_HACcomplete_k4
k:4
sizes: [ 188 3168  977  766]
clusterID_HACcomplete_k4
k:4
sizes: [3668  348  149  934]
clusterID_HACcomplete_k4
k:4
sizes: [ 353 3855  351  540]
clusterID_HACcomplete_k4
k:4
sizes: [3262   88  725 1024]
clusterID_HACcomplete_k4
k:4
sizes: [ 324 3475  841  459]
clusterID_HACcomplete_k4
k:4
sizes: [3661  877  170  391]
clusterID_HACcomplete_k4
k:4
sizes: [3214  867  295  723]
clusterID_HACcomplete_k4
k:4
sizes: [2683 1104  949  363]
clusterID_HACcomplete_k4
k:4
sizes: [ 573 3290  259  977]
clusterID_HACcomplete_k4
k:4
sizes: [3828  374  276  621]
clusterID_HACcomplete_k4
k:4
sizes: [4154  421  182  342]
clusterID_HACcomplete_k4
k:4
sizes: [ 276  442 1226 3155]
clusterID_HACcomplete_k4
k:4
sizes: [3792  383  500  424]
clusterID_HACcomplete_k4
k:4
sizes: [ 641 3540  606  312]
clusterID_HACcomplete_k4
k:4
sizes: [ 322 3220  371 1186]
clusterID_HACcomplete_k4
k:4
sizes: [ 477 3102  330 1190]
clusterID_HACcomplete_k4
k:4
sizes: [ 181  295 3215 1408]
clusterID_HACcomplete_k4
k:4
sizes: [ 336 3331  560  872]
clusterID_HACcomplete_k4
k:4
sizes: [ 259 3746  248  846]
clusterID_HACcomplete_k4
k:4
sizes: [4167  203  125  604]
clusterID_HACcomplete_k4
k:4
sizes: [ 257 3384  745  713]
clusterID_HACcomplete_k4
k:4
sizes: [3309  512  343  935]
clusterID_HACcomplete_k4
k:4
sizes: [ 516  792 3164  627]
clusterID_HACcomplete_k4
k:4
sizes: [3810  282  221  786]
clusterID_HACcomplete_k4
k:4
sizes: [3084  980   99  936]
clusterID_HACcomplete_k4
k:4
sizes: [ 882 3432  165  620]
clusterID_HACcomplete_k4
k:4
sizes: [3777  103  204 1015]
clusterID_HACcomplete_k4
k:4
sizes: [3802  528  397  372]
clusterID_HACcomplete_k4
k:4
sizes: [ 429 3843  554  273]
clusterID_HACcomplete_k4
k:4
sizes: [ 116  476 3907  600]
clusterID_HACcomplete_k4
k:4
sizes: [3874  262   49  914]
clusterID_HACcomplete_k4
k:4
sizes: [ 577  339  467 3716]
clusterID_HACcomplete_k4
k:4
sizes: [ 371 3045   95 1588]
clusterID_HACcomplete_k4
k:4
sizes: [ 338 3803  298  660]
clusterID_HACcomplete_k4
k:4
sizes: [ 371  823 3493  412]
clusterID_HACcomplete_k4
k:4
sizes: [ 612 1154  101 3232]
clusterID_HACcomplete_k4
k:4
sizes: [ 348  213 2889 1649]
clusterID_HACcomplete_k4
k:4
sizes: [3081 1195   58  765]
clusterID_HACcomplete_k4
k:4
sizes: [3885  652  257  305]
clusterID_HACcomplete_k4
k:4
sizes: [  92  506 1173 3328]
clusterID_HACcomplete_k4
k:4
sizes: [ 204  438  841 3616]
clusterID_HACcomplete_k4
k:4
sizes: [ 555 3764  124  656]
clusterID_HACcomplete_k4
k:4
sizes: [4049  142  228  680]
clusterID_HACcomplete_k4
k:4
sizes: [3899  270  457  473]
clusterID_HACcomplete_k4
k:4
sizes: [ 439  142 3170 1348]
clusterID_HACcomplete_k4
k:4
sizes: [ 127 3739  322  911]
clusterID_HACcomplete_k4
k:4
sizes: [  86  476 3051 1486]
clusterID_HACcomplete_k4
k:4
sizes: [  60  567 3378 1094]
clusterID_HACcomplete_k4
k:4
sizes: [ 436  849  150 3664]
clusterID_HACcomplete_k4
k:4
sizes: [3921  436  105  637]
clusterID_HACcomplete_k4
k:4
sizes: [ 302 3260  271 1266]
clusterID_HACcomplete_k4
k:4
sizes: [ 613 3438  330  718]
clusterID_HACcomplete_k4
k:4
sizes: [3100 1041  221  737]
clusterID_HACcomplete_k4
k:4
sizes: [  67  686 1164 3182]
clusterID_HACcomplete_k4
k:4
sizes: [ 588  279  466 3766]
clusterID_HACcomplete_k4
k:4
sizes: [ 294  307 1077 3421]k:2
sizes: [3889 1210]
clusterID_HACcomplete_k2
k:2
sizes: [ 495 4604]
clusterID_HACcomplete_k2
k:2
sizes: [4060 1039]
clusterID_HACcomplete_k2
k:2
sizes: [3730 1369]
clusterID_HACcomplete_k2
k:2
sizes: [ 543 4556]
clusterID_HACcomplete_k2
k:2
sizes: [4152  947]
clusterID_HACcomplete_k2
k:2
sizes: [ 796 4303]
clusterID_HACcomplete_k2
k:2
sizes: [4026 1073]
clusterID_HACcomplete_k2
k:2
sizes: [4220  879]
clusterID_HACcomplete_k2
k:2
sizes: [3976 1123]
clusterID_HACcomplete_k2
k:2
sizes: [4160  939]
clusterID_HACcomplete_k2
k:2
sizes: [4084 1015]
clusterID_HACcomplete_k2
k:2
sizes: [4137  962]
clusterID_HACcomplete_k2
k:2
sizes: [3783 1316]
clusterID_HACcomplete_k2
k:2
sizes: [ 487 4612]
clusterID_HACcomplete_k2
k:2
sizes: [3789 1310]
clusterID_HACcomplete_k2
k:2
sizes: [ 425 4674]
clusterID_HACcomplete_k2
k:2
sizes: [4084 1015]
clusterID_HACcomplete_k2
k:2
sizes: [ 639 4460]
clusterID_HACcomplete_k2
k:2
sizes: [4004 1095]
clusterID_HACcomplete_k2
k:2
sizes: [ 429 4670]
clusterID_HACcomplete_k2
k:2
sizes: [ 573 4526]
clusterID_HACcomplete_k2
k:2
sizes: [ 446 4653]
clusterID_HACcomplete_k2
k:2
sizes: [4103  996]
clusterID_HACcomplete_k2
k:2
sizes: [4064 1035]
clusterID_HACcomplete_k2
k:2
sizes: [4248  851]
clusterID_HACcomplete_k2
k:2
sizes: [4232  867]
clusterID_HACcomplete_k2
k:2
sizes: [3737 1362]
clusterID_HACcomplete_k2
k:2
sizes: [3809 1290]
clusterID_HACcomplete_k2
k:2
sizes: [ 351 4748]
clusterID_HACcomplete_k2
k:2
sizes: [3920 1179]
clusterID_HACcomplete_k2
k:2
sizes: [ 533 4566]
clusterID_HACcomplete_k2
k:2
sizes: [ 354 4745]
clusterID_HACcomplete_k2
k:2
sizes: [4030 1069]
clusterID_HACcomplete_k2
k:2
sizes: [ 701 4398]
clusterID_HACcomplete_k2
k:2
sizes: [4155  944]
clusterID_HACcomplete_k2
k:2
sizes: [ 434 4665]
clusterID_HACcomplete_k2
k:2
sizes: [4153  946]
clusterID_HACcomplete_k2
k:2
sizes: [4237  862]
clusterID_HACcomplete_k2
k:2
sizes: [ 587 4512]
clusterID_HACcomplete_k2
k:2
sizes: [4056 1043]
clusterID_HACcomplete_k2
k:2
sizes: [4211  888]
clusterID_HACcomplete_k2
k:2
sizes: [ 310 4789]
clusterID_HACcomplete_k2
k:2
sizes: [ 298 4801]
clusterID_HACcomplete_k2
k:2
sizes: [3960 1139]
clusterID_HACcomplete_k2
k:2
sizes: [ 731 4368]
clusterID_HACcomplete_k2
k:2
sizes: [4312  787]
clusterID_HACcomplete_k2
k:2
sizes: [4024 1075]
clusterID_HACcomplete_k2
k:2
sizes: [ 925 4174]
clusterID_HACcomplete_k2
k:2
sizes: [ 292 4807]
clusterID_HACcomplete_k2
k:2
sizes: [ 751 4348]
clusterID_HACcomplete_k2
k:2
sizes: [ 842 4257]
clusterID_HACcomplete_k2
k:2
sizes: [ 827 4272]
clusterID_HACcomplete_k2
k:2
sizes: [ 764 4335]
clusterID_HACcomplete_k2
k:2
sizes: [4114  985]
clusterID_HACcomplete_k2
k:2
sizes: [3655 1444]
clusterID_HACcomplete_k2
k:2
sizes: [ 483 4616]
clusterID_HACcomplete_k2
k:2
sizes: [ 279 4820]
clusterID_HACcomplete_k2
k:2
sizes: [ 530 4569]
clusterID_HACcomplete_k2
k:2
sizes: [3938 1161]
clusterID_HACcomplete_k2
k:2
sizes: [ 449 4650]
clusterID_HACcomplete_k2
k:2
sizes: [3922 1177]
clusterID_HACcomplete_k2
k:2
sizes: [4060 1039]
clusterID_HACcomplete_k2
k:2
sizes: [ 281 4818]
clusterID_HACcomplete_k2
k:2
sizes: [ 266 4833]
clusterID_HACcomplete_k2
k:2
sizes: [ 282 4817]
clusterID_HACcomplete_k2
k:2
sizes: [3758 1341]
clusterID_HACcomplete_k2
k:2
sizes: [ 461 4638]
clusterID_HACcomplete_k2
k:2
sizes: [ 674 4425]
clusterID_HACcomplete_k2
k:2
sizes: [ 530 4569]
clusterID_HACcomplete_k2
k:2
sizes: [4026 1073]
clusterID_HACcomplete_k2
k:2
sizes: [ 581 4518]
clusterID_HACcomplete_k2
k:2
sizes: [4235  864]
clusterID_HACcomplete_k2
k:2
sizes: [3807 1292]
clusterID_HACcomplete_k2
k:2
sizes: [ 313 4786]
clusterID_HACcomplete_k2
k:2
sizes: [ 728 4371]

[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  2.0min

k:2
sizes: [4056 1043]
clusterID_HACcomplete_k2
k:2
sizes: [4048 1051]
clusterID_HACcomplete_k2
k:2
sizes: [ 527 4572]
clusterID_HACcomplete_k2
k:2
sizes: [ 308 4791]
clusterID_HACcomplete_k2
k:2
sizes: [3894 1205]
clusterID_HACcomplete_k2
k:2
sizes: [ 777 4322]
clusterID_HACcomplete_k2
k:2
sizes: [4203  896]
clusterID_HACcomplete_k2
k:2
sizes: [ 629 4470]
clusterID_HACcomplete_k2
k:2
sizes: [3960 1139]
clusterID_HACcomplete_k2
k:2
sizes: [3741 1358]
clusterID_HACcomplete_k2
k:2
sizes: [ 582 4517]
clusterID_HACcomplete_k2
k:2
sizes: [ 648 4451]
clusterID_HACcomplete_k2
k:2
sizes: [3952 1147]
clusterID_HACcomplete_k2
k:2
sizes: [4084 1015]
clusterID_HACcomplete_k2
k:2
sizes: [ 289 4810]
clusterID_HACcomplete_k2
k:2
sizes: [3831 1268]
clusterID_HACcomplete_k2
k:2
sizes: [ 618 4481]
clusterID_HACcomplete_k2
k:2
sizes: [3836 1263]
clusterID_HACcomplete_k2
k:2
sizes: [4051 1048]
clusterID_HACcomplete_k2
k:2
sizes: [ 504 4595]
clusterID_HACcomplete_k2
k:2
sizes: [3691 1408]
clusterID_HACcomplete_k2
k:2
sizes: [4063 1036]
clusterID_HACcomplete_k2
k:2
sizes: [4123  976]
clusterID_HACcomplete_k2
k:2
sizes: [ 294 4805]
clusterID_HACcomplete_k2
k:2
sizes: [ 710 4389]
clusterID_HACcomplete_k2
k:2
sizes: [3909 1190]
clusterID_HACcomplete_k2
k:2
sizes: [ 353 4746]
clusterID_HACcomplete_k2
k:2
sizes: [ 449 4650]
clusterID_HACcomplete_k2
k:2
sizes: [ 731 4368]
clusterID_HACcomplete_k2
k:2
sizes: [4024 1075]
clusterID_HACcomplete_k2
k:2
sizes: [ 810 4289]
clusterID_HACcomplete_k2
k:2
sizes: [ 456 4643]
clusterID_HACcomplete_k2
k:2
sizes: [3773 1326]
clusterID_HACcomplete_k2
k:2
sizes: [4062 1037]
clusterID_HACcomplete_k2
k:2
sizes: [3737 1362]
clusterID_HACcomplete_k2
k:2
sizes: [ 284 4815]
clusterID_HACcomplete_k2
k:2
sizes: [3953 1146]
clusterID_HACcomplete_k2
k:2
sizes: [4087 1012]
clusterID_HACcomplete_k2
k:2
sizes: [3933 1166]
clusterID_HACcomplete_k2
k:2
sizes: [ 413 4686]
clusterID_HACcomplete_k2
k:2
sizes: [4107  992]
clusterID_HACcomplete_k2
k:2
sizes: [ 316 4783]
clusterID_HACcomplete_k2
k:2
sizes: [ 888 4211]
clusterID_HACcomplete_k2
k:2
sizes: [3720 1379]
clusterID_HACcomplete_k2
k:2
sizes: [4133  966]
clusterID_HACcomplete_k2
k:2
sizes: [ 291 4808]
clusterID_HACcomplete_k2
k:2
sizes: [3963 1136]
clusterID_HACcomplete_k2
k:2
sizes: [4089 1010]
clusterID_HACcomplete_k2
k:2
sizes: [ 812 4287]
clusterID_HACcomplete_k2
k:2
sizes: [ 355 4744]
clusterID_HACcomplete_k2
k:2
sizes: [4043 1056]
clusterID_HACcomplete_k2
k:2
sizes: [3987 1112]
clusterID_HACcomplete_k2
k:2
sizes: [4199  900]
clusterID_HACcomplete_k2
k:2
sizes: [ 587 4512]
clusterID_HACcomplete_k2
k:2
sizes: [3567 1532]
clusterID_HACcomplete_k2
k:2
sizes: [ 372 4727]
clusterID_HACcomplete_k2
k:2
sizes: [ 404 4695]
clusterID_HACcomplete_k2
k:2
sizes: [ 183 4916]
clusterID_HACcomplete_k2
k:2
sizes: [ 465 4634]
clusterID_HACcomplete_k2
k:2
sizes: [4407  692]
clusterID_HACcomplete_k2
k:2
sizes: [3852 1247]
clusterID_HACcomplete_k2
k:2
sizes: [4224  875]
clusterID_HACcomplete_k2
k:2
sizes: [3951 1148]
clusterID_HACcomplete_k2
k:2
sizes: [ 492 4607]
clusterID_HACcomplete_k2
k:2
sizes: [ 485 4614]
clusterID_HACcomplete_k2
k:2
sizes: [4054 1045]
clusterID_HACcomplete_k2
k:2
sizes: [ 285 4814]
clusterID_HACcomplete_k2
k:2
sizes: [4050 1049]
clusterID_HACcomplete_k2
k:2
sizes: [3930 1169]
clusterID_HACcomplete_k2
k:2
sizes: [4101  998]
clusterID_HACcomplete_k2
k:2
sizes: [4102  997]
clusterID_HACcomplete_k2
k:2
sizes: [ 591 4508]
clusterID_HACcomplete_k2
k:2
sizes: [3673 1426]
clusterID_HACcomplete_k2
k:2
sizes: [ 661 4438]
clusterID_HACcomplete_k2
k:2
sizes: [ 370 4729]
clusterID_HACcomplete_k2
k:2
sizes: [ 819 4280]
clusterID_HACcomplete_k2
k:2
sizes: [3919 1180]
clusterID_HACcomplete_k2
k:2
sizes: [4182  917]
clusterID_HACcomplete_k2
k:2
sizes: [4147  952]
clusterID_HACcomplete_k2
k:2
sizes: [ 634 4465]
clusterID_HACcomplete_k2
k:2
sizes: [ 659 4440]
clusterID_HACcomplete_k2
k:2
sizes: [ 500 4599]
clusterID_HACcomplete_k2
k:2
sizes: [4231  868]
clusterID_HACcomplete_k2
k:2
sizes: [ 766 4333]
clusterID_HACcomplete_k2
k:2
sizes: [4033 1066]
clusterID_HACcomplete_k2
k:2
sizes: [3973 1126]
clusterID_HACcomplete_k2
k:2
sizes: [ 389 4710]
clusterID_HACcomplete_k2
k:2
sizes: [3982 1117]
clusterID_HACcomplete_k2
k:2
sizes: [ 739 4360]
clusterID_HACcomplete_k2
k:2
sizes: [ 726 4373]
clusterID_HACcomplete_k2
k:2
sizes: [3874 1225]
clusterID_HACcomplete_k2
k:2
sizes: [ 407 4692]
clusterID_HACcomplete_k2
k:2
sizes: [3205 1894]
clusterID_HACcomplete_k2
k:2
sizes: [3845 1254]
clusterID_HACcomplete_k2
k:2
sizes: [ 665 4434]
clusterID_HACcomplete_k2
k:2
sizes: [ 865 4234]
clusterID_HACcomplete_k2
k:2
sizes: [ 571 4528]
clusterID_HACcomplete_k2
k:2
sizes: [ 391 4708]
clusterID_HACcomplete_k2
k:2
sizes: [ 307 4792]
clusterID_HACcomplete_k2
k:2
sizes: [3583 1516]
clusterID_HACcomplete_k2
k:2
sizes: [ 896 4203]
clusterID_HACcomplete_k2
k:2
sizes: [ 698 4401]
clusterID_HACcomplete_k2
k:2
sizes: [ 528 4571]
clusterID_HACcomplete_k2
k:2
sizes: [3732 1367]
clusterID_HACcomplete_k2
k:2
sizes: [ 636 4463]
clusterID_HACcomplete_k2
k:2
sizes: [4114  985]
clusterID_HACcomplete_k2
k:2
sizes: [ 895 4204]
clusterID_HACcomplete_k2
k:2
sizes: [3861 1238]
clusterID_HACcomplete_k2
k:2
sizes: [ 425 4674]
clusterID_HACcomplete_k2
k:2
sizes: [ 670 4429]
clusterID_HACcomplete_k2
k:2
sizes: [ 229 4870]
clusterID_HACcomplete_k2
k:2
sizes: [ 222 4877]
clusterID_HACcomplete_k2
k:2
sizes: [3957 1142]
clusterID_HACcomplete_k2
k:2
sizes: [4198  901]
clusterID_HACcomplete_k2
k:2
sizes: [3934 1165]
clusterID_HACcomplete_k2
k:2
sizes: [ 755 4344]
clusterID_HACcomplete_k2
k:2
sizes: [3924 1175]
clusterID_HACcomplete_k2
k:2
sizes: [3601 1498]
clusterID_HACcomplete_k2
k:2
sizes: [ 229 4870]
clusterID_HACcomplete_k2
k:2
sizes: [3914 1185]
clusterID_HACcomplete_k2
k:2
sizes: [ 731 4368]
clusterID_HACcomplete_k2
k:2
sizes: [4098 1001]
clusterID_HACcomplete_k2
k:2
sizes: [4097 1002]
clusterID_HACcomplete_k2
k:3
sizes: [ 324 3526 1249]
clusterID_HACcomplete_k3
k:3
sizes: [3867  639  593]
clusterID_HACcomplete_k3
k:3
sizes: [ 311 1050 3738]
clusterID_HACcomplete_k3
k:3
sizes: [4032  209  858]
clusterID_HACcomplete_k3
k:3
sizes: [3993  331  775]
clusterID_HACcomplete_k3
k:3
sizes: [ 426 3481 1192]
clusterID_HACcomplete_k3
k:3
sizes: [ 367 3347 1385]
clusterID_HACcomplete_k3
k:3
sizes: [ 220 3620 1259]
clusterID_HACcomplete_k3
k:3
sizes: [4123  236  740]
clusterID_HACcomplete_k3
k:3
sizes: [ 831 1069 3199]
clusterID_HACcomplete_k3
k:3
sizes: [3758  177 1164]
clusterID_HACcomplete_k3
k:3
sizes: [3977  160  962]
clusterID_HACcomplete_k3
k:3
sizes: [4007  666  426]
clusterID_HACcomplete_k3
k:3
sizes: [ 621 3728  750]
clusterID_HACcomplete_k3
k:3
sizes: [ 400 3570 1129]
clusterID_HACcomplete_k3
k:3
sizes: [ 333 3505 1261]
clusterID_HACcomplete_k3
k:3
sizes: [3970  254  875]
clusterID_HACcomplete_k3
k:3
sizes: [ 320 3577 1202]
clusterID_HACcomplete_k3
k:3
sizes: [3864  203 1032]
clusterID_HACcomplete_k3
k:3
sizes: [3871  218 1010]
clusterID_HACcomplete_k3
k:3
sizes: [4135  220  744]
clusterID_HACcomplete_k3
k:3
sizes: [ 430 2944 1725]
clusterID_HACcomplete_k3
k:3
sizes: [3973  748  378]
clusterID_HACcomplete_k3
k:3
sizes: [3889  315  895]
clusterID_HACcomplete_k3
k:3
sizes: [4102  488  509]
clusterID_HACcomplete_k3
k:3
sizes: [ 470  822 3807]
clusterID_HACcomplete_k3
k:3
sizes: [3891  438  770]
clusterID_HACcomplete_k3
k:3
sizes: [ 243 3497 1359]
clusterID_HACcomplete_k3
k:3
sizes: [ 482 3498 1119]
clusterID_HACcomplete_k3
k:3
sizes: [3686  809  604]
clusterID_HACcomplete_k3
k:3
sizes: [ 371 3685 1043]
clusterID_HACcomplete_k3
k:3
sizes: [ 458 3138 1503]
clusterID_HACcomplete_k3
k:3
sizes: [ 455 3249 1395]
clusterID_HACcomplete_k3
k:3
sizes: [ 235 3632 1232]
clusterID_HACcomplete_k3
k:3
sizes: [3717  422  960]
clusterID_HACcomplete_k3
k:3
sizes: [4056  375  668]
clusterID_HACcomplete_k3
k:3
sizes: [ 683  748 3668]
clusterID_HACcomplete_k3
k:3
sizes: [3883  512  704]
clusterID_HACcomplete_k3
k:3
sizes: [ 318 3510 1271]
clusterID_HACcomplete_k3
k:3
sizes: [ 501 3526 1072]
clusterID_HACcomplete_k3
k:3
sizes: [ 416  623 4060]
clusterID_HACcomplete_k3
k:3
sizes: [ 678 2788 1633]
clusterID_HACcomplete_k3
k:3
sizes: [ 220 3533 1346]
clusterID_HACcomplete_k3
k:3
sizes: [ 686 3516  897]
clusterID_HACcomplete_k3
k:3
sizes: [ 210 3931  958]
clusterID_HACcomplete_k3
k:3
sizes: [3777  813  509]
clusterID_HACcomplete_k3
k:3
sizes: [ 477  835 3787]
clusterID_HACcomplete_k3
k:3
sizes: [4345  250  504]
clusterID_HACcomplete_k3
k:3
sizes: [ 640  549 3910]
clusterID_HACcomplete_k3
k:3
sizes: [ 421 3578 1100]
clusterID_HACcomplete_k3
k:3
sizes: [ 304 3359 1436]
clusterID_HACcomplete_k3
k:3
sizes: [ 391 3477 1231]
clusterID_HACcomplete_k3
k:3
sizes: [ 721 3058 1320]
clusterID_HACcomplete_k3
k:3
sizes: [ 299 3249 1551]
clusterID_HACcomplete_k3
k:3
sizes: [4132  168  799]
clusterID_HACcomplete_k3
k:3
sizes: [ 277  633 4189]
clusterID_HACcomplete_k3
k:2
sizes: [ 707 4392]
clusterID_HACcomplete_k3
k:3
sizes: [ 686 3091 1322]
clusterID_HACcomplete_k3
k:3
sizes: [4247  322  530]
clusterID_HACcomplete_k3
k:3
sizes: [ 530 3802  767]
clusterID_HACcomplete_k3
k:3
sizes: [ 351 3720 1028]
clusterID_HACcomplete_k3
k:3
sizes: [ 600 3650  849]
clusterID_HACcomplete_k3
k:3
sizes: [ 375 3369 1355]
clusterID_HACcomplete_k3
k:3
sizes: [3930  930  239]
clusterID_HACcomplete_k3
k:3
sizes: [ 747  502 3850]
clusterID_HACcomplete_k3
k:3
sizes: [ 723 3292 1084]
clusterID_HACcomplete_k3
k:3
sizes: [3631  128 1340]
clusterID_HACcomplete_k3
k:3
sizes: [4099  481  519]
clusterID_HACcomplete_k3
k:3
sizes: [ 259 3624 1216]
clusterID_HACcomplete_k3
k:3
sizes: [3534  183 1382]
clusterID_HACcomplete_k3
k:3
sizes: [3793  402  904]
clusterID_HACcomplete_k3
k:3
sizes: [ 359 3386 1354]
clusterID_HACcomplete_k3
k:3
sizes: [ 553 3196 1350]
clusterID_HACcomplete_k3
k:3
sizes: [ 154 3332 1613]
clusterID_HACcomplete_k3
k:3
sizes: [4276  701  122]
clusterID_HACcomplete_k3
k:3
sizes: [4251  403  445]
clusterID_HACcomplete_k3
k:3
sizes: [ 578 3493 1028]
clusterID_HACcomplete_k3
k:3
sizes: [4064  309  726]
clusterID_HACcomplete_k3
k:3
sizes: [ 442 3711  946]
clusterID_HACcomplete_k3
k:3
sizes: [ 412 3818  869]
clusterID_HACcomplete_k3
k:3
sizes: [ 463 3504 1132]
clusterID_HACcomplete_k3
k:3
sizes: [4099  302  698]
clusterID_HACcomplete_k3
k:3
sizes: [3547 1076  476]
clusterID_HACcomplete_k3
k:3
sizes: [3896  519  684]
clusterID_HACcomplete_k3
k:3
sizes: [ 529 3424 1146]
clusterID_HACcomplete_k3
k:3
sizes: [4069  371  659]
clusterID_HACcomplete_k3
k:3
sizes: [3481  217 1401]
clusterID_HACcomplete_k3
k:3
sizes: [ 361 3193 1545]
clusterID_HACcomplete_k3
k:3
sizes: [ 716  283 4100]
clusterID_HACcomplete_k3
k:3
sizes: [ 391 3858  850]
clusterID_HACcomplete_k3
k:3
sizes: [ 468  685 3946]
clusterID_HACcomplete_k3
k:3
sizes: [4195  252  652]
clusterID_HACcomplete_k3
k:3
sizes: [ 359 3358 1382]
clusterID_HACcomplete_k3
k:3
sizes: [4021  334  744]
clusterID_HACcomplete_k3
k:3
sizes: [4091  392  616]
clusterID_HACcomplete_k3
k:3
sizes: [ 649 3203 1247]
clusterID_HACcomplete_k3
k:3
sizes: [ 605 2869 1625]
clusterID_HACcomplete_k3
k:3
sizes: [3989  301  809]
clusterID_HACcomplete_k3
k:3
sizes: [3802   86 1211]
clusterID_HACcomplete_k3
k:3
sizes: [ 306 3501 1292]
clusterID_HACcomplete_k3
k:3
sizes: [4052  160  887]
clusterID_HACcomplete_k3
k:3
sizes: [3601  235 1263]
clusterID_HACcomplete_k3
k:3
sizes: [3839  485  775]
clusterID_HACcomplete_k3
k:3
sizes: [ 569 3742  788]
clusterID_HACcomplete_k3
k:3
sizes: [3836  384  879]
clusterID_HACcomplete_k3
k:3
sizes: [4053  191  855]
clusterID_HACcomplete_k3
k:3
sizes: [3908  161 1030]
clusterID_HACcomplete_k3
k:3
sizes: [ 442 3404 1253]
clusterID_HACcomplete_k3
k:3
sizes: [3803  300  996]
clusterID_HACcomplete_k3
k:3
sizes: [3817 1089  193]
clusterID_HACcomplete_k3
k:3
sizes: [3842  307  950]
clusterID_HACcomplete_k3
k:3
sizes: [ 691  961 3447]
clusterID_HACcomplete_k3
k:3
sizes: [ 363 3454 1282]
clusterID_HACcomplete_k3
k:3
sizes: [4050  426  623]
clusterID_HACcomplete_k3
k:3
sizes: [ 591 3283 1225]
clusterID_HACcomplete_k3
k:3
sizes: [ 364 4116  619]
clusterID_HACcomplete_k3
k:3
sizes: [ 571  834 3694]
clusterID_HACcomplete_k3
k:3
sizes: [3850  535  714]
clusterID_HACcomplete_k3
k:3
sizes: [ 295 3588 1216]
clusterID_HACcomplete_k3
k:3
sizes: [4032  371  696]
clusterID_HACcomplete_k3
k:3
sizes: [4168  303  628]
clusterID_HACcomplete_k3
k:3
sizes: [3862  291  946]
clusterID_HACcomplete_k3
k:3
sizes: [3826  381  892]
clusterID_HACcomplete_k3
k:3
sizes: [4143  276  680]
clusterID_HACcomplete_k3
k:4
sizes: [ 564 3546  342  647]
clusterID_HACcomplete_k4
k:4
sizes: [  60  818 3020 1201]
clusterID_HACcomplete_k4
k:4
sizes: [ 104  681  357 3957]
clusterID_HACcomplete_k4
k:4
sizes: [ 573 3635  219  672]
clusterID_HACcomplete_k4
k:4
sizes: [3588  176 1048  287]
clusterID_HACcomplete_k4
k:4
sizes: [3836  491  155  617]
clusterID_HACcomplete_k4
k:4
sizes: [ 415  284 2827 1573]
clusterID_HACcomplete_k4
k:4
sizes: [ 234  430 3461  974]
clusterID_HACcomplete_k4
k:4
sizes: [ 132  884 2857 1226]
clusterID_HACcomplete_k4
k:4
sizes: [ 128  399 3558 1014]
clusterID_HACcomplete_k4
k:4
sizes: [ 305 3202  259 1333]
clusterID_HACcomplete_k4
k:4
sizes: [ 509 3806  307  477]
clusterID_HACcomplete_k4
k:4
sizes: [3603  342  481  673]
clusterID_HACcomplete_k4
k:4
sizes: [3777  384  477  461]
clusterID_HACcomplete_k4
k:4
sizes: [ 185  273 3508 1133]
clusterID_HACcomplete_k4
k:4
sizes: [4052  128  469  450]
clusterID_HACcomplete_k4
k:4
sizes: [ 267  499  646 3687]
clusterID_HACcomplete_k4
k:4
sizes: [  61  980  525 3533]
clusterID_HACcomplete_k4
k:4
sizes: [3391  183  500 1025]
clusterID_HACcomplete_k4
k:4
sizes: [3596  129  709  665]
clusterID_HACcomplete_k4
k:4
sizes: [2970 1289  197  643]
clusterID_HACcomplete_k4
k:4
sizes: [3701  430  662  306]
clusterID_HACcomplete_k4
k:4
sizes: [   9  510 3707  873]
clusterID_HACcomplete_k4
k:4
sizes: [ 276 3361  633  829]
clusterID_HACcomplete_k4
k:4
sizes: [2779 1404  279  637]
clusterID_HACcomplete_k4
k:4
sizes: [3978  319  457  345]
clusterID_HACcomplete_k4
k:4
sizes: [ 205  681 3639  574]
clusterID_HACcomplete_k4
k:4
sizes: [ 410 3393 1034  262]
clusterID_HACcomplete_k4
k:4
sizes: [ 394 3481  209 1015]
clusterID_HACcomplete_k4
k:4
sizes: [  83  627  849 3540]
clusterID_HACcomplete_k4
k:4
sizes: [3492  242  756  609]
clusterID_HACcomplete_k4
k:4
sizes: [ 717 3426  549  407]
clusterID_HACcomplete_k4
k:4
sizes: [ 461 3114  160 1364]
clusterID_HACcomplete_k4
k:4
sizes: [ 370 3479  422  828]
clusterID_HACcomplete_k4
k:4
sizes: [3975  314  188  622]
clusterID_HACcomplete_k4
k:4
sizes: [ 660  572  706 3161]
clusterID_HACcomplete_k4
k:4
sizes: [ 303 3523  590  683]
clusterID_HACcomplete_k4
k:4
sizes: [3797  423  453  426]
clusterID_HACcomplete_k4
k:4
sizes: [2936 1218  254  691]
clusterID_HACcomplete_k4
k:4
sizes: [ 641 3712  478  268]
clusterID_HACcomplete_k4
k:4
sizes: [ 442 1101  191 3365]
clusterID_HACcomplete_k4
k:4
sizes: [ 266 3251  737  845]
clusterID_HACcomplete_k4
k:4
sizes: [3271 1157  173  498]
clusterID_HACcomplete_k4
k:4
sizes: [3692  395  209  803]
clusterID_HACcomplete_k4
k:4
sizes: [ 144  431  775 3749]
clusterID_HACcomplete_k4
k:4
sizes: [ 217 3446  246 1190]
clusterID_HACcomplete_k4
k:4
sizes: [  67  449 3764  819]
clusterID_HACcomplete_k4
k:4
sizes: [4090  241  226  542]
clusterID_HACcomplete_k4
k:4
sizes: [ 323 3764  736  276]
clusterID_HACcomplete_k4
k:4
sizes: [ 214  675 3374  836]
clusterID_HACcomplete_k4
k:4
sizes: [ 183 3333  805  778]
clusterID_HACcomplete_k4
k:4
sizes: [1145 2946  346  662]
clusterID_HACcomplete_k4
k:4
sizes: [ 247 3635  359  858]
clusterID_HACcomplete_k4
k:4
sizes: [4161  120  448  370]
clusterID_HACcomplete_k4
k:4
sizes: [3911  368  205  615]
clusterID_HACcomplete_k4
k:4
sizes: [ 358  528  391 3822]
clusterID_HACcomplete_k4
k:4
sizes: [3333  903   78  785]
clusterID_HACcomplete_k4
k:4
sizes: [3920  176  376  627]
clusterID_HACcomplete_k4
k:4
sizes: [ 187  575 3395  942]
clusterID_HACcomplete_k4
k:4
sizes: [ 451 1148  170 3330]
clusterID_HACcomplete_k4
k:4
sizes: [ 386  328  375 4010]
clusterID_HACcomplete_k4
k:4
sizes: [1058 3214  226  601]
clusterID_HACcomplete_k4
k:4
sizes: [ 446 3548  625  480]
clusterID_HACcomplete_k4
k:4
sizes: [ 499 3549  312  739]
clusterID_HACcomplete_k4
k:4
sizes: [ 638 3830   75  556]
clusterID_HACcomplete_k4
k:4
sizes: [ 190  486 3390 1033]
clusterID_HACcomplete_k4
k:4
sizes: [ 190  714 3439  756]
clusterID_HACcomplete_k4
k:4

[Parallel(n_jobs=-1)]: Done 866 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:  3.1min finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.

                          K      ARI    QS_mean       L_ci       U_ci  \
0  clusterID_HACcomplete_k5  0.60242 -10.004237 -39.197139  43.672357

   %-discarded  %-mismatch duration
0          0.0         0.5  184.67s

[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    1.3s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    9.8s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   26.4s
[Parallel(n_jobs=-1)]: Done 272 tasks      | elapsed:   47.4s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:  8.9min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  9.5min
[Parallel(n_jobs=-1)]: Done 866 tasks      | elapsed: 12.9min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed: 13.8min finished

                          K       ARI   QS_mean       L_ci       U_ci  \
0  clusterID_HACcomplete_k7  0.453659 -9.691443 -32.581285  34.485728

   %-discarded  %-mismatch duration
0          0.0         2.4  826.13s
Done computing BQS

,K,ARI,QS_mean,L_ci,U_ci,%-discarded,%-mismatch,duration,b
0,clusterID_HACcomplete_k2,0.439034,-10.995460,-33.953417,44.759848,0.0,0.0,927.36s,1000
1,clusterID_HACcomplete_k3,0.653186,-10.428633,-39.732411,49.786513,0.0,0.1,168.42s,1000
2,clusterID_HACcomplete_k4,0.631826,-10.206347,-38.558203,47.642731,0.0,0.4,2194.70s,1000
3,clusterID_HACcomplete_k5,0.602420,-10.004237,-39.197139,43.672357,0.0,0.5,184.67s,1000
4,clusterID_HACcomplete_k7,0.453659,-9.691443,-32.581285,34.485728,0.0,2.4,826.13s,1000

# BOOTSTRAP WITHOUT PARALLELIZATION
# -------------------------------------------

def compute_BQS(data, byvar, algorithm, s, n_bootstrap=100, randomstate=RandomSeed):
    n=data.shape[0]  # sample size

    qs_list = []
    comment_list = []
    print(f'A:{s}')

    # Step 1 - Bootstrap Scores
    start = time.time()
    for b in range(n_bootstrap):
        # Independent Bootstrap Sample
        # Bootstrap means sampling with replacement. Each bootstrap sample is the same size as the original dataset, but some rows appear multiple times and some don’t appear at all.
        # The number of duplicates depends on randomness, but roughly 1/3 of included points will appear multiple times in this implementation.
        sample_idx = np.random.choice(n, n, replace = True) # draw bootstrap sample indices (~63%) and than copies from the sample to replace the missing values and create a same size dataset.
        sample_data = data.iloc[sample_idx].reset_index(drop=True) # Select the data from the dataset based on the bootstrap indicdes
        
        # Run clustering
        if algorithm == 'kmeans':
            n_clusters = s   
            sample_data, clusterID = kmeans_clustering(sample_data, n_clusters, randomstate, byvar)
            if b == 1: # Print time estimation of 1 computation
                elapsed = time.time()-start
                print(f"Bootstrap iteration {b}/{n_bootstrap} - elapsed time: {elapsed:.2f}s")
                
        elif algorithm == 'HAC_ward':
            n_clusters = s  
            sample_data, clusterID = HAC_ward_clustering(sample_data, n_clusters)
            print(f'B:{clusterID}')
            if b%50 ==0: #Print every X resamples
                elapsed = time.time()-start
                print(f"Bootstrap iteration {b}/{n_bootstrap} - elapsed time: {elapsed:.2f}s")
                
        elif algorithm == 'Spectral_Density':
            setting = s
            sample_data, clusterID = run_spectral_clustering(dataset, setting, columns_gp, RandomSeed)
            if b%50 ==0: #Print every X resamples
                elapsed = time.time()-start
                print(f"Bootstrap iteration {b}/{n_bootstrap} - elapsed time: {elapsed:.2f}s")

        else:
            raise ValueError(f"Unknown algorithm: {algorithm}")
                
        # Compute QS as before
        sample_QS, sample_comment = suppress_print(compute_QS, sample_data, byvar, clusterID)
        qs_list.append(sample_QS) # Store QS of bootstrap sample
        comment_list.append(sample_comment) # Store comments from bootstrap samples

    # Resampling criteria: Check if fraction of invalid QS <25% of b
    # Solutions are invalid for e.g. singular mixture component, non convergence) 
    n_nonempty = sum([1 for c in comment_list if c.strip() != ""])  # Count non-empty comments
    proportion_nonempty = n_nonempty / n_bootstrap*100 # Converge counts to proportion

    qs_array = np.array(qs_list) #Converge QS scores to array

    # Step 2 - Average bootstrap score
    W = qs_array.mean() # Expected QS score

    # Step 3 - Standardize bootstrap statistics
    R = np.sqrt(n)*(qs_array - W)
    
    alpha = 0.05 #α = confidence level (e.g., 0.05 for 95% CI). Which is the CI indicated in the figures of the paper.
    L = np.quantile(R, alpha/2)  # Lower bound
    U = np.quantile(R, 1-alpha/2) # Upper bound

    # Step 4 - Bootstrap Quadratic Score
    # 'Rather than selecting cluster configurations achieving the largest estimated W. We propose to select argmax(L).
    # BQH criteria = argmax(L)
    BQS = L

    print('C:{clusterID}')
    results = {'K' : clusterID,
            'QS_mean': W,
            'L_ci': L,
            'U_ci': U,
            'all_QS': qs_array,
            '%-discarded': proportion_nonempty
             }

    print(pd.DataFrame([results])[['K', 'QS_mean', 'L_ci', 'U_ci', '%-discarded']])
    print(f"Total elapsed time: {time.time()-start:.2f}s")

    return clusterID, BQS, results

# APPENDIX

## Compute BQS with Scaled Data

In [67]:
scales = ['unscaled', 'div10', 'StandardScaled']

if algorithm == 'kmeans':
    for k in range(2,10): 
        dataset, clusterID = kmeans_clustering(dataset, k, RandomSeed, columns_gp)
        
    for scaling in scales: 
            data_scaled = dataset
            if scaling == 'unscaled':
                data_scaled
            elif scaling == 'div10':
                data_scaled[columns_gp] = dataset[columns_gp]/10
            elif scaling == 'StandardScaled':
                scaler = StandardScaler()
                data_scaled[columns_gp] = pd.DataFrame(
                    scaler.fit_transform(dataset[columns_gp]),      # Only values are transformed
                    columns=columns_gp,            # Keep original column names
                    index=dataset[columns_gp].index                 # Optional: keep original index
                )
            else:   raise ValueError(f"Unknown scaling: {scaling}")

            data_scaled, clusterID = kmeans_clustering(data_scaled, k, RandomSeed, columns_gp)

            print(scaling)
            for n_clust in range(2,10):
                clusterID, qs_bootstrapped, bqs_results = compute_BQS_ARI_inParallel(data_scaled, columns_gp, algorithm, s = n_clust)
                BQS.append({'K': clusterID, 'BQS':qs_bootstrapped})
                bqs = pd.DataFrame([bqs_results])[['K', 'ARI', 'QS_mean', 'L_ci', 'U_ci', '%-discarded', 'duration', 'b']]
                bqs.insert(0, 'scaling', scaling)
                bqs_list.append(bqs)

    os.system('say "BQS Scaling test Computed!"')
    pd.concat(bqs_list, ignore_index=True)